# Generated by Django 4.1 on 2023-12-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Группа",
            fields=[
                (
                    "группа",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("факультет", models.CharField(max_length=255)),
                ("специальность", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Зачетки",
            fields=[
                ("номер_зачетки", models.AutoField(primary_key=True, serialize=False)),
                ("ФИО", models.CharField(max_length=255)),
                ("группа", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Студенты",
            fields=[
                (
                    "ФИО",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("год_рождения", models.DateField()),
                ("адрес", models.TextField()),
                ("телефон", models.CharField(max_length=20)),
            ],
        ),
    ]
