/* JS */ gapi.loaded_0(function(_){var window=this;
try{
_.l=function(a){throw a;};_.n=void 0;_.p=!0;_.q=null;_.v=!1;_.ba=function(){return function(a){return a}};_.x=function(){return function(){}};_.da=function(a){return function(c){this[a]=c}};_.z=function(a){return function(){return this[a]}};_.A=function(a){return function(){return a}};
_.fa=function(a){var c=typeof a;if("object"==c)if(a){if(a instanceof window.Array)return"array";if(a instanceof window.Object)return c;var f=window.Object.prototype.toString.call(a);if("[object Window]"==f)return"object";if("[object Array]"==f||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==f||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==c&&"undefined"==typeof a.call)return"object";return c};_.ma=function(a){return a!==_.n};_.oa=function(a){return"array"==(0,_.fa)(a)};_.pa=function(a){var c=typeof a;return"object"==c&&a!=_.q||"function"==c};_.ua=function(a,c,f){return a.call.apply(a.bind,arguments)};
_.va=function(a,c,f){a||(0,_.l)((0,window.Error)());if(2<arguments.length){var g=window.Array.prototype.slice.call(arguments,2);return function(){var f=window.Array.prototype.slice.call(arguments);window.Array.prototype.unshift.apply(f,g);return a.apply(c,f)}}return function(){return a.apply(c,arguments)}};_.G=function(a,c,f){_.G=window.Function.prototype.bind&&-1!=window.Function.prototype.bind.toString().indexOf("native code")?_.ua:_.va;return _.G.apply(_.q,arguments)};
_.wa=function(a,c){var f=window.Array.prototype.slice.call(arguments,1);return function(){var c=window.Array.prototype.slice.call(arguments);c.unshift.apply(c,f);return a.apply(this,c)}};_.J=function(a,c){function f(){}f.prototype=c.prototype;a.D=c.prototype;a.prototype=new f;a.prototype.constructor=a};_._DumpException=function(a){(0,_.l)(a)};_.ya=_.ya||{};_.Da=this;_.Ea="closure_uid_"+window.Math.floor(2147483648*window.Math.random()).toString(36);_.Ga=window.Date.now||function(){return+new window.Date}; window.Function.prototype.bind=window.Function.prototype.bind||function(a,c){if(1<arguments.length){var f=window.Array.prototype.slice.call(arguments,1);f.unshift(this,a);return _.G.apply(_.q,f)}return(0,_.G)(this,a)};
_.Ka=window.gapi||{};_.La=window.gadgets||{};_.L=window.osapi=window.osapi||{};
}catch(e){_._DumpException(e)}
try{
window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},client:{jsonpOverride:_.v},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:_.v},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:_.v},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/u/:session_index:/_/pages/badge"},":socialhost:":"https://plusone.google.com",card:{params:{s:"#",userid:"&"},url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton"},
plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator"}},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{methods:{"chili.people.list":_.p,"pos.plusones.list":_.p,"pos.plusones.get":_.p,"chili.people.get":_.p,"pos.plusones.insert":_.p,"chili.activities.list":_.p,"pos.plusones.delete":_.p,"chili.activities.get":_.p,"chili.activities.search":_.p,"pos.plusones.getSignupState":_.p},
requestCache:{enabled:_.p},versions:{chili:"v1",pos:"v1"},rpc:"/rpc",root:"https://www.googleapis.com","root-1p":"https://clients6.google.com",sessionCache:{enabled:_.p},transport:{isProxyShared:_.p},xd3:"/static/proxy.html",developerKey:"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ",auth:{useInterimAuth:_.v}}});

window.___jsl=window.___jsl||{};(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"onload"},iframes:{card:{url:":socialhost:/u/:session_index:/_/hovercard/card"}}});
}catch(e){_._DumpException(e)}
try{
_.N=function(a,c,f){a=a.split(".");f=f||_.Da;!(a[0]in f)&&f.execScript&&f.execScript("var "+a[0]);for(var g;a.length&&(g=a.shift());)!a.length&&(0,_.ma)(c)?f[g]=c:f=f[g]?f[g]:f[g]={}};_.Oa=function(a,c,f){return a[c]=a[c]||f};_.Pa=function(a){for(var c=0;c<this.length;c++)if(this[c]===a)return c;return-1};_.Qa=function(){var a;if((a=window.Object.create)&&_.Ua.test(a))a=a(_.q);else{a={};for(var c in a)a[c]=_.n}return a};_.Va=function(){return window.___jsl=window.___jsl||{}};
_.Wa=function(a){var c=(0,_.Va)();c[a]=c[a]||[];return c[a]};_.Xa=function(a){var c=(0,_.Va)();c.cfg=!a&&c.cfg||{};return c.cfg};_.db=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};_.eb=function(a,c){if(c)for(var f in c)c.hasOwnProperty(f)&&(a[f]&&c[f]&&"object"===typeof a[f]&&"object"===typeof c[f]&&!(0,_.db)(a[f])&&!(0,_.db)(c[f])?(0,_.eb)(a[f],c[f]):c[f]&&"object"===typeof c[f]?(a[f]=(0,_.db)(c[f])?[]:{},(0,_.eb)(a[f],c[f])):a[f]=c[f])};
_.fb=function(a){(0,_.Xa)(_.p);var c=window.___gcfg,f=(0,_.Wa)("cu");if(c&&c!==window.___gu){var g={};(0,_.eb)(g,c);f.push(g);window.___gu=c}var c=(0,_.Wa)("cu"),h=window.document.scripts||window.document.getElementsByTagName("script")||[],g=[],j=[],m=(0,_.Va)().u;m&&j.push(m);(0,_.Va)().us&&j.push.apply(j,(0,_.Va)().us);for(m=0;m<h.length;++m)for(var o=h[m],t=0;t<j.length;++t)o.src&&0==o.src.indexOf(j[t])&&g.push(o);0==g.length&&h[h.length-1].src&&g.push(h[h.length-1]);for(h=0;h<g.length;++h)if(!g[h].getAttribute("gapi_processed")){g[h].setAttribute("gapi_processed",
_.p);(j=g[h])?(m=j.nodeType,j=3==m||4==m?j.nodeValue:j.textContent||j.innerText||j.innerHTML||""):j=_.n;if(j){for(;0==j.charCodeAt(j.length-1);)j=j.substring(0,j.length-1);m=_.n;try{m=(new window.Function("return ("+j+"\n)"))()}catch(u){}if("object"===typeof m)j=m;else{try{m=(new window.Function("return ({"+j+"\n})"))()}catch(w){}j="object"===typeof m?m:{}}}else j=_.n;j&&c.push(j)}a&&(g={},(0,_.eb)(g,a),f.push(g));g=(0,_.Wa)("cd");a=0;for(c=g.length;a<c;++a)(0,_.eb)((0,_.Xa)(),g[a]);g=(0,_.Wa)("ci");
a=0;for(c=g.length;a<c;++a)(0,_.eb)((0,_.Xa)(),g[a]);a=0;for(c=f.length;a<c;++a)(0,_.eb)((0,_.Xa)(),f[a])};_.O=function(a,c){if(!a)return(0,_.Xa)();for(var f=a.split("/"),g=(0,_.Xa)(),h=0,j=f.length;g&&"object"===typeof g&&h<j;++h)g=g[f[h]];return h===f.length&&g!==_.n?g:c};_.kb=function(a,c){var f=a;if("string"===typeof a){for(var g=f={},h=a.split("/"),j=0,m=h.length;j<m-1;++j)var o={},g=g[h[j]]=o;g[h[j]]=c}(0,_.fb)(f)};
_.lb=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),(0,_.Oa)(_.qb,"ci",[]).push(a),window.__GOOGLEAPIS=_.n)};_.Q=function(a,c){c="function"==typeof _.vb&&(0,_.vb)(a,c)||c;(0,_.N)(a,c,_.n)};
_.wb=window;_.xb=window.document;_.Ua=/\[native code\]/;_.yb=(0,_.Oa)(_.wb,"gapi",{});_.qb=(0,_.Oa)(_.wb,"___jsl",(0,_.Qa)());(0,_.Oa)(_.qb,"I",0);(0,_.Oa)(_.qb,"hel",10);_.lb&&(0,_.lb)();(0,_.fb)();(0,_.Q)("gapi.config.get",_.O);(0,_.Q)("gapi.config.update",_.kb);
}catch(e){_._DumpException(e)}
try{

}catch(e){_._DumpException(e)}
try{

}catch(e){_._DumpException(e)}
try{
_.Jb={go:{},fa:{}};_.Ob={go:{},fa:{}};
}catch(e){_._DumpException(e)}
try{

}catch(e){_._DumpException(e)}
try{
_.R=_.R||{};
}catch(e){_._DumpException(e)}
try{
_.R=_.R||{};_.R.xg=function(a,c,f){for(var g=[],h=2,j=arguments.length;h<j;++h)g.push(arguments[h]);return function(){for(var f=g.slice(),h=0,j=arguments.length;h<j;++h)f.push(arguments[h]);return c.apply(a,f)}};_.R.ai=function(a){var c,f,g={};for(c=0;f=a[c];++c)g[f]=f;return g};

}catch(e){_._DumpException(e)}
try{
_.cc=function(a,c){return window.String.fromCharCode(c)};_.R=_.R||{};_.gc={"0":_.v,10:_.p,13:_.p,34:_.p,39:_.p,60:_.p,62:_.p,92:_.p,8232:_.p,8233:_.p,65282:_.p,65287:_.p,65308:_.p,65310:_.p,65340:_.p};_.R.escape=function(a,c){if(a){if("string"===typeof a)return _.R.uh(a);if("array"===typeof a)for(var f=0,g=a.length;f<g;++f)a[f]=_.R.escape(a[f]);else if("object"===typeof a&&c){f={};for(g in a)a.hasOwnProperty(g)&&(f[_.R.uh(g)]=_.R.escape(a[g],_.p));return f}}return a}; _.R.uh=function(a){if(!a)return a;for(var c=[],f,g,h=0,j=a.length;h<j;++h)f=a.charCodeAt(h),g=_.gc[f],g===_.p?c.push("&#",f,";"):g!==_.v&&c.push(a.charAt(h));return c.join("")};_.R.rz=function(a){return!a?a:a.replace(/&#([0-9]+);/g,_.cc)};

}catch(e){_._DumpException(e)}
try{
_.ic=_.ic||{};_.ic.lv=function(){var a=0,c=0;window.self.innerHeight?(a=window.self.innerWidth,c=window.self.innerHeight):window.document.documentElement&&window.document.documentElement.clientHeight?(a=window.document.documentElement.clientWidth,c=window.document.documentElement.clientHeight):window.document.body&&(a=window.document.body.clientWidth,c=window.document.body.clientHeight);return{width:a,height:c}};

}catch(e){_._DumpException(e)}
try{
_.jc=function(a,c){window.getComputedStyle(a,"").getPropertyValue(c).match(/^([0-9]+)/);return(0,window.parseInt)(window.RegExp.$1,10)};_.ic=_.ic||{};
_.ic.em=function(){var a=_.ic.lv().height,c=window.document.body,f=window.document.documentElement;if("CSS1Compat"===window.document.compatMode&&f.scrollHeight)return f.scrollHeight!==a?f.scrollHeight:f.offsetHeight;if(0<=window.navigator.userAgent.indexOf("AppleWebKit")){a=0;for(c=[window.document.body];0<c.length;){var g=c.shift(),f=g.childNodes;if("undefined"!==typeof g.style){var h=g.style.overflowY;h||(h=(h=window.document.defaultView.getComputedStyle(g,_.q))?h.overflowY:_.q);if("visible"!=h&&
"inherit"!=h&&(h=g.style.height,h||(h=(h=window.document.defaultView.getComputedStyle(g,_.q))?h.height:""),0<h.length&&"auto"!=h))continue}for(g=0;g<f.length;g++){h=f[g];if("undefined"!==typeof h.offsetTop&&"undefined"!==typeof h.offsetHeight)var j=h.offsetTop+h.offsetHeight+(0,_.jc)(h,"margin-bottom"),a=window.Math.max(a,j);c.push(h)}}return a+(0,_.jc)(window.document.body,"border-bottom")+(0,_.jc)(window.document.body,"margin-bottom")+(0,_.jc)(window.document.body,"padding-bottom")}if(c&&f)return g= f.scrollHeight,h=f.offsetHeight,f.clientHeight!==h&&(g=c.scrollHeight,h=c.offsetHeight),g>a?g>h?g:h:g<h?g:h};

}catch(e){_._DumpException(e)}
try{
_.Xb=function(a,c){if(!(a<_.Yb)&&_._console$$inline_395)if(2===a&&_._console$$inline_395.warn)_._console$$inline_395.warn(c);else if(3===a&&_._console$$inline_395.error)try{_._console$$inline_395.error(c)}catch(f){}else _._console$$inline_395.log&&_._console$$inline_395.log(c)};_.Zb=function(a){(0,_.Xb)(1,a)};_.bc=function(a){(0,_.Xb)(2,a)};_.Ib=function(a){(0,_.Xb)(3,a)};_.Zb.INFO=1;_.Zb.WARNING=2;_.Zb.NONE=4;_.Yb=1; _._console$$inline_395=window.console?window.console:window.opera?window.opera.postError:_.n;

}catch(e){_._DumpException(e)}
try{
_.R=_.R||{};_.R.fh=function(a,c,f,g){"undefined"!=typeof a.addEventListener?a.addEventListener(c,f,g):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+c,f):(0,_.bc)("cannot attachBrowserEvent: "+c)};_.R.Kw=function(a,c,f,g){a.removeEventListener?a.removeEventListener(c,f,g):a.detachEvent?a.detachEvent("on"+c,f):(0,_.bc)("cannot removeBrowserEvent: "+c)};

}catch(e){_._DumpException(e)}
try{
_.tc=function(){function a(){h[0]=1732584193;h[1]=4023233417;h[2]=2562383102;h[3]=271733878;h[4]=3285377520;w=u=0}function c(a){for(var c=m,f=0;64>f;f+=4)c[f/4]=a[f]<<24|a[f+1]<<16|a[f+2]<<8|a[f+3];for(f=16;80>f;f++)c[f]=((c[f-3]^c[f-8]^c[f-14]^c[f-16])<<1|(c[f-3]^c[f-8]^c[f-14]^c[f-16])>>>31)&4294967295;for(var a=h[0],g=h[1],j=h[2],o=h[3],t=h[4],w,u,f=0;80>f;f++)40>f?20>f?(w=o^g&(j^o),u=1518500249):(w=g^j^o,u=1859775393):60>f?(w=g&j|o&(g|j),u=2400959708):(w=g^j^o,u=3395469782),w=((a<<5|a>>>27)&4294967295)+
w+t+u+c[f]&4294967295,t=o,o=j,j=(g<<30|g>>>2)&4294967295,g=a,a=w;h[0]=h[0]+a&4294967295;h[1]=h[1]+g&4294967295;h[2]=h[2]+j&4294967295;h[3]=h[3]+o&4294967295;h[4]=h[4]+t&4294967295}function f(a,f){if("string"===typeof a){for(var a=(0,window.unescape)((0,window.encodeURIComponent)(a)),g=[],h=0,m=a.length;h<m;++h)g.push(a.charCodeAt(h));a=g}f||(f=a.length);g=0;if(0==u)for(;g+64<f;)c(a.slice(g,g+64)),g+=64,w+=64;for(;g<f;)if(j[u++]=a[g++],w++,64==u){u=0;for(c(j);g+64<f;)c(a.slice(g,g+64)),g+=64,w+=64}}
function g(){var a=[],g=8*w;56>u?f(o,56-u):f(o,64-(u-56));for(var m=63;56<=m;m--)j[m]=g&255,g>>>=8;c(j);for(m=g=0;5>m;m++)for(var t=24;0<=t;t-=8)a[g++]=h[m]>>t&255;return a}for(var h=[],j=[],m=[],o=[128],t=1;64>t;++t)o[t]=0;var u,w;a();return{reset:a,update:f,wy:g,cj:function(){for(var a=g(),c="",f=0;f<a.length;f++)c+="0123456789ABCDEF".charAt(window.Math.floor(a[f]/16))+"0123456789ABCDEF".charAt(a[f]%16);return c}}};

}catch(e){_._DumpException(e)}
try{
_.vc=function(a){var c=(0,_.tc)();c.update(a);return c.cj()};_.wc=window.crypto;
if(_.wc&&"function"==typeof _.wc.getRandomValues)_.uc=function(){var a=new window.Uint32Array(1);_.wc.getRandomValues(a);return(0,window.Number)("0."+a[0])};else{_.xc=(0,_.O)("random/maxObserveMousemove");_.xc==_.q&&(_.xc=-1);_.yc=0;_.zc=window.Math.random();_.Ec=1;_.Fc=1E6*(window.screen.width*window.screen.width+window.screen.height);_.Gc=function(a){var a=a||window.event,c=a.screenX+a.clientX<<16,c=c+(a.screenY+a.clientY),c=c*((new window.Date).getTime()%1E6);_.Ec=_.Ec*c%_.Fc;0<_.xc&&++_.yc==_.xc&&
_.R.Kw(window,"mousemove",_.Gc,_.v)};0!=_.xc&&_.R.fh(window,"mousemove",_.Gc,_.v);_.Hc=(0,_.vc)(window.document.cookie+"|"+window.document.location+"|"+(new window.Date).getTime()+"|"+_.zc);_.uc=function(){var a=_.Ec,a=a+(0,window.parseInt)(_.Hc.substr(0,20),16);_.Hc=(0,_.vc)(_.Hc);return a/(_.Fc+window.Math.pow(16,20))}};
(0,_.Q)("shindig.random",_.uc);
}catch(e){_._DumpException(e)}
try{
_.R=_.R||{};_.Ic=[];_.R.cz=function(a){_.Ic.push(a)};_.R.jz=function(){for(var a=0,c=_.Ic.length;a<c;++a)_.Ic[a]()};
}catch(e){_._DumpException(e)}
try{
_.Kc=window.gadgets&&window.gadgets.config&&window.gadgets.config.get;_.Kc&&(0,_.kb)((0,_.Kc)());_.Jc={ea:function(a,c,f){f&&f((0,_.O)())},get:function(a){return(0,_.O)(a)},update:function(a,c){c&&(0,_.l)("Config replacement is not supported");(0,_.kb)(a)},xa:(0,_.x)()};
(0,_.Q)("gadgets.config.register",_.Jc.ea);(0,_.Q)("gadgets.config.get",_.Jc.get);(0,_.Q)("gadgets.config.init",_.Jc.xa);(0,_.Q)("gadgets.config.update",_.Jc.update);
}catch(e){_._DumpException(e)}
try{
if(window.JSON&&window.JSON.parse&&window.JSON.stringify){_.Qb=function(a){return this[a]};_.Wb=/___$/;_.Pb={parse:function(a){try{return window.JSON.parse(a)}catch(c){return _.v}},stringify:function(a){function c(a){return f.call(this,a,_.Qb)}var f=window.JSON.stringify,g=window.Array.prototype.toJSON&&'"[{\\"x\\": 1}]"'===f([{x:1}])?c:f;try{return g(a,function(a,c){return!_.Wb.test(a)?c:_.n})}catch(h){return _.q}}}};
if(!window.JSON||!window.JSON.parse||!window.JSON.stringify)_.Pb=function(){function a(a){return 10>a?"0"+a:a}function c(a){var h,j,m;h=/[\"\\\x00-\x1f\x7f-\x9f]/g;switch(typeof a){case "string":return h.test(a)?'"'+a.replace(h,function(a){var c=f[a];if(c)return c;c=a.charCodeAt();return"\\u00"+window.Math.floor(c/16).toString(16)+(c%16).toString(16)})+'"':'"'+a+'"';case "number":return(0,window.isFinite)(a)?(0,window.String)(a):"null";case "boolean":case "null":return(0,window.String)(a);case "object":if(!a)return"null";
h=[];if("number"===typeof a.length&&!a.propertyIsEnumerable("length")){m=a.length;for(j=0;j<m;j+=1)h.push(c(a[j])||"null");return"["+h.join(",")+"]"}for(j in a)!/___$/.test(j)&&a.hasOwnProperty(j)&&"string"===typeof j&&(m=c(a[j]))&&h.push(c(j)+":"+m);return"{"+h.join(",")+"}"}return""}window.Date.prototype.toJSON=function(){return[this.getUTCFullYear(),"-",a(this.getUTCMonth()+1),"-",a(this.getUTCDate()),"T",a(this.getUTCHours()),":",a(this.getUTCMinutes()),":",a(this.getUTCSeconds()),"Z"].join("")};
var f={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return{stringify:c,parse:function(a){return/^[\],:{}\s]*$/.test(a.replace(/\\["\\\/b-u]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))?eval("("+a+")"):_.v}}}();
_.Pb.vp=function(a){var c={};if(a===_.q||a===_.n)return c;for(var f in a)if(a.hasOwnProperty(f)){var g=a[f];_.q===g||_.n===g||(c[f]="string"===typeof g?g:_.Pb.stringify(g))}return c};(0,_.Q)("gadgets.json.flatten",_.Pb.vp);(0,_.Q)("gadgets.json.parse",_.Pb.parse);(0,_.Q)("gadgets.json.stringify",_.Pb.stringify);(0,_.Q)("gadgets.json.flatten",_.Pb.vp);(0,_.Q)("gadgets.json.parse",_.Pb.parse);(0,_.Q)("gadgets.json.stringify",_.Pb.stringify);

}catch(e){_._DumpException(e)}
try{
_.R=_.R||{};_.hc=_.q;
_.R.wa=function(a){var c="undefined"===typeof a;if(_.hc!==_.q&&c)return _.hc;for(var f={},a=a||window.document.location.href,g=a.indexOf("?"),h=a.indexOf("#"),a=(-1===h?a.substr(g+1):[a.substr(g+1,h-g-1),"&",a.substr(h+1)].join("")).split("&"),g=window.decodeURIComponent?window.decodeURIComponent:window.unescape,h=0,j=a.length;h<j;++h){var m=a[h].indexOf("=");if(-1!==m){var o=a[h].substring(0,m),m=a[h].substring(m+1),m=m.replace(/\+/g," ");try{f[o]=g(m)}catch(t){}}}c&&(_.hc=f);return f};_.R.wa();
(0,_.Q)("gadgets.util.getUrlParameters",_.R.wa);
}catch(e){_._DumpException(e)}
try{
_.Lc=window.gapi&&window.gapi.util||{};
}catch(e){_._DumpException(e)}
try{
_.Lc.Va=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);/^\w*:\/\//.test(a)||(a=window.location.href);var c=a.substring(a.indexOf("://")+3),f=c.indexOf("/");-1!=f&&(c=c.substring(0,f));var a=a.substring(0,a.indexOf("://")),f="",g=c.indexOf(":");if(-1!=g){var h=c.substring(g+1),c=c.substring(0,g);if("http"===a&&"80"!==h||"https"===a&&"443"!==h)f=":"+h}return a+"://"+c+f};

}catch(e){_._DumpException(e)}
try{
if(window.gapi&&window.gapi.rpc){_.Nc=window.gapi.rpc;_.Nc.call=_.Nc.call;_.Nc.ea=_.Nc.register;_.Nc.he=_.Nc.unregister;_.Nc.Pe=_.Nc.setup;_.Nc.tx=_.Nc.sw;_.Mc=_.Nc}else{_.Uc=function(a){if(a.f in{})return _.v;var c=a.t,f=_.Oc[a.r],a=a.origin;return f&&(f.Lg===c||!f.Lg&&!c)&&(a===f.origin||"*"===f.origin)};_.$c=function(a,c,f){a=(0,_.Vc)(a);_.Yc[a.name]={Iu:c,Xh:a.Xh,Cx:f||_.Uc};(0,_.Zc)()};_.cd=function(a){var c=a.c;if(!c)return(0,_.x)();var f=a.r,g=a.g?"legacy__":"";return function(){var a=[].slice.call(arguments,
0);_.ad?a.unshift(f,g+"__cb",_.q,c):a.unshift(f,g+"__cb"+c,_.q);_.bd.apply(_.q,a)}};_.qd=function(a,c,f,g){var h=_.dd,j=_.ed,m=_.Oc[c],o=h,t=(0,_.fd)(c);if(m&&".."!==c){if(t.Qm){if(!(j=_.Oc[c].Rw)){j=_.q;j=_.gd?_.gd.substring(1).split("/"):[_.dd];o=j.length-1;for(c=window.parent;c!==window.top;){var u=c.parent;if(!o--){for(var w=_.q,C=u.frames.length,F=0;F<C;++F)u.frames[F]==c&&(w=F);j.unshift("{"+w+"}")}c=u}j="/"+j.join("/")}o=j}else o=h="..";j=m.Lg}m=o;if(g&&t){o=_.Uc;if(t.Qm)var o=t.id.split("/"),
M=o[o.length-1],K=t.origin,o=function(a){var c=a.origin;return a.f==M&&(K==c||"*"==K)};_.ad?_.hd["_"+ ++_.pd]=[g,o]:(0,_.$c)("__cb"+(0,window.String)(++_.pd),g,o);g=_.pd}else g=_.q;f={s:a,f:h,r:m,t:j,c:g,a:f};a=(0,_.Vc)(a);f.s=a.name;f.g=a.Xh;return f};_.vd=function(a){var c=_.Oc[a];if(c&&c.pd){var f=c.In;c.In=[];if(_.rd)f.length&&(f=(0,_.qd)("_processBatch",a,[f]),_.sd.send(a,_.Pb.stringify(f),c.origin));else for(;f.length;)_.sd.send(a,_.Pb.stringify(f.shift()),c.origin)}};_.Vc=function(a){return 0===
a.indexOf("legacy__")?{name:a.substring(8),Xh:_.p}:{name:a,Xh:_.v}};_.Zc=function(){for(var a=0,c;c=_.wd[a];++a){var f=c.Jg,g=f.s,h=_.Yc[g]||_.Yc["*"];if(h&&(_.wd.splice(a,1),--a,f.origin=c.origin,c=(0,_.cd)(f),f.callback=c,h.Cx(f))){if("__cb"!==g&&!!h.Xh!=!!f.g)break;f=h.Iu.apply(f,f.a);f!==_.n&&c(f)}}};_.fd=function(a){var c=_.v,a=a.split("|"),f=a[0];0<=f.indexOf("/")&&(c=_.p);return{id:f,origin:a[1]||"*",Qm:c}};_.zd=function(a,c){var f=(0,_.fd)(a),a=f.id;if(!_.Oc.hasOwnProperty(a)){var g=_.ed,
h=_.q;f.Qm?(g=_.q,h=f.origin):".."!==a?(g=window.document.getElementById(a).src,h=_.Lc.Va(g),g=(0,_.xd)(g).rpctoken):h=_.Lc.Va(_.yd);f.origin&&(h=f.origin);_.Oc[a]={Lg:g,In:[],origin:h,Rw:c,rr:function(){var c=a;_.Oc[c].pd=1;(0,_.vd)(c)}};_.sd.Pe(a,_.Oc[a].rr)}return _.Oc[a].rr};_.Ad=function(){return"function"===typeof window.postMessage||"object"===typeof window.postMessage};_.bd=function(a,c,f,g){a=a||"..";(0,_.zd)(a);var a=a.split("|",1)[0],h=[].slice.call(arguments,3),h=(0,_.qd)(c,a,h,f);_.Oc[a].In.push(h);
var j=a;_.Bd[j]||(_.Bd[j]=window.setTimeout(function(){_.Bd[j]=_.v;(0,_.vd)(j)},0))};_.Cd={call:_.bd,ea:_.$c,he:function(a){a=(0,_.Vc)(a);delete _.Yc[a.name]},Pe:_.zd,tx:_.Ad};if((0,_.Ad)()){_.rd=_.v;_.pd=0;_.wd=[];_.Oc={};_.Yc={};_.xd=_.R.wa;_.Dd=(0,_.xd)();_.ed=_.Dd.rpctoken;_.yd=_.Dd.parent||window.document.referrer;_.dd=window!==window.top&&window.name||"..";_.gd=_.q;_.Bd={};_.Ed={Gd:function(a,c){var f=_.Pb.parse(a);_.wd.push({Jg:f,origin:c});(0,_.Zc)()},mv:function(a){var c=window;"/"==a.charAt(0)&&
(a=a.substring(1),c=window.top);for(a=a.split("/");a.length;){var f;f=a.shift();"{"==f.charAt(0)&&"}"==f.charAt(f.length-1)&&(f=f.substring(1,f.length-1));if(".."===f)c=c.parent;else if(".."!==f&&c.frames[f])c=c.frames[f],"postMessage"in c||(0,_.l)("Not a window");else return _.q}return c},mn:_.dd,Kp:function(a){return(a=_.Oc[a])&&a.Lg},b:function(a){_.gd=a}};_.Fd=function(a){a=_.Pb.parse(a);return a!=_.q&&"object"===typeof a&&!!a.g};_.Hd=function(a){var c=(0,window.String)(a.data),f=0!==c.indexOf("!_");
f||(c=c.substring(2));var g=(0,_.Fd)(c);if(f==g){if(!g&&(f=c,g=_.q,0==f.indexOf("{h:'")&&f.indexOf("'}")==f.length-2&&(g=(0,window.unescape)(f.substring(4,f.length-2))),f=g)){if(_.Gd[f])_.Gd[f]();return}var h=a.origin;window.setTimeout(function(){_.Ed.Gd(c,h)},0)}};_.Gd={};_.Id=_.q;(_.Id=window.addEventListener)?(0,_.Id)("message",_.Hd,_.v):(_.Id=window.attachEvent)&&(0,_.Id)("onmessage",_.Hd);window.___jsl=window.___jsl||{};_.Jd=window.___jsl;_.Jd.RPMQ=_.Jd.RPMQ||[];_.Jd.RPMQ.push(_.Hd);if(window!==
window.parent){_.Sd=window.parent;_.Td="{h:'"+(0,window.escape)(window.name)+"'}";_.Ud=(0,_.Fd)(_.Td)?"":"!_";_.Sd.postMessage(_.Ud+_.Td,"*")}_.sd={Pe:function(a,c){".."==a?c():_.Gd[a]=c},send:function(a,c,f){var a=_.Ed.mv(a),g=(0,_.Fd)(c)?"":"!_";a.postMessage(g+c,f)}};_.hd={};_.ad=_.p;(0,_.$c)("__cb",function(a,c){var f=_.hd["_"+a];f&&f[1](this)&&f[0].call(this,c)},(0,_.A)(_.p));(0,_.$c)("_processBatch",function(a){for(;a.length;){var c=a.shift();_.wd.push({Jg:c,origin:this.origin})}(0,_.Zc)()}, (0,_.A)(_.p));(0,_.zd)("..")}_.Mc=_.Cd}_.Vd=_.Mc;

}catch(e){_._DumpException(e)}
try{

}catch(e){_._DumpException(e)}
try{
_.Yd=_.Yd||{};_.Yd.Fr=_.q;_.Yd.Qq=_.q;_.Yd.Ej=_.q;_.Yd.frameElement=_.q;_.Yd=_.Yd||{};
if(!_.Yd.zo){_.ae=function(a){var c=_.Pb.parse(a.data);if(c&&c.f){var f=_.S.Md(c.f);(!_.Zd||!("undefined"!==typeof a.origin?a.origin!==f:a.domain!==/^.+:\/\/([^:]+).*/.exec(f)[1]))&&(0,_.$d)(c,a.origin)}};_.Zd=_.p;_.Yd.zo={Ep:(0,_.A)("wpm"),b:(0,_.A)(_.p),xa:function(a,c){_.Jc.ea("rpc",_.q,function(a){if("true"===(0,window.String)((a&&a.rpc||{}).disableForceSecure))_.Zd=_.v});_.$d=a;_.be=c;"undefined"!=typeof window.addEventListener?window.addEventListener("message",_.ae,_.v):"undefined"!=typeof window.attachEvent&&
window.attachEvent("onmessage",_.ae);window.___jsl=window.___jsl||{};var f=window.___jsl;f.RPMQ=f.RPMQ||[];f.RPMQ.push(_.ae);(0,_.be)("..",_.p);return _.p},Pe:function(a){(0,_.be)(a,_.p);return _.p},call:function(a,c,f){var g=_.S.Md(a),h=_.S.Po(a);g?window.setTimeout(function(){h.postMessage(_.Pb.stringify(f),g)},0):".."!=a&&(0,_.Ib)("No relay set (used as window.postMessage targetOrigin), cannot send cross-domain message");return _.p}}};
_.Yd=_.Yd||{};
if(!_.Yd.lj){_.ce=_.Yd;_.fe=function(a,c){function f(){a.apply({},arguments)}_.de[c]=_.de[c]||f;return _.ee+"."+c};_.Be=function(){if(_.ge===_.q&&window.document.body&&_.se){var a=_.se+"?cb="+window.Math.random()+"&origin="+_.te+"&jsl=1",c=window.document.createElement("div");c.style.height="1px";c.style.width="1px";a='<object height="1" width="1" id="'+_.ue+'" type="application/x-shockwave-flash"><param name="allowScriptAccess" value="always"></param><param name="movie" value="'+a+'"></param><embed type="application/x-shockwave-flash" allowScriptAccess="always" src="'+
a+'" height="1" width="1"></embed></object>';window.document.body.appendChild(c);c.innerHTML=a;_.ge=c.firstChild}++_.ve;_.we!==_.q&&(_.ge!==_.q||50<=_.ve)?window.clearTimeout(_.we):_.we=window.setTimeout(_.Be,100)};_.Ge=function(){_.Ce[".."]||((0,_.De)(".."),_.Ee++,50<=_.Ee&&_.Fe!==_.q?(window.clearTimeout(_.Fe),_.Fe=_.q):_.Fe=window.setTimeout(_.Ge,100))};_.Ie=function(){if(_.ge!==_.q&&_.ge.setup)for(;0<_.He.length;){var a=_.He.shift(),c=a.vx;_.ge.setup(a.Lg,".."===c?_.S.Tk:c,".."===c?"INNER":"OUTER")}_.we!==
_.q&&window.clearTimeout(_.we);_.we=_.q};_.Je=function(){!_.Ce[".."]&&_.Fe===_.q&&(_.Fe=window.setTimeout(_.Ge,100))};_.Ke=function(a,c,f){var c=_.S.Md(a),g=_.S.Id(a);_.ge["sendMessage_"+(".."===a?_.S.Tk:a)+"_"+g+"_"+(".."===a?"INNER":"OUTER")].call(_.ge,_.Pb.stringify(f),c);return _.p};_.Ze=function(a,c){var f=_.Pb.parse(a),g=f._scr;g?((0,_.Le)(g,_.p),_.Ce[g]=_.p,".."!==g&&(0,_.De)(g,_.p)):window.setTimeout(function(){(0,_.Ye)(f,c)},0)};_.De=function(a,c){var f=_.S.Tk,g={};g._scr=c?"..":f;g._pnt=
f;(0,_.Ke)(a,f,g)};_.ue="___xpcswf";_.se=_.q;_.$e=_.v;_.Ye=_.q;_.Le=_.q;_.ge=_.q;_.He=[];_.we=_.q;_.ve=0;_.Ee=0;_.Fe=_.q;_.Ce={};_.te=window.location.protocol+"//"+window.location.host;window.___jsl=window.___jsl||{};_.af=window.___jsl._fm={};_.ee="___jsl._fm";_.de=_.af;_.Jc.ea("rpc",_.q,function(a){_.$e&&(_.se=a&&a.rpc&&a.rpc.commSwf||"//xpc.googleusercontent.com/gadgets/xpc.swf")});(0,_.fe)(_.Ie,"ready");(0,_.fe)(_.Je,"setupDone");(0,_.fe)(_.Ze,"receiveMessage");_.ce.lj={Ep:(0,_.A)("flash"),b:(0,_.A)(_.p), xa:function(a,c){_.Ye=a;_.Le=c;return _.$e=_.p},Pe:function(a,c){_.He.push({Lg:c,vx:a});_.ge===_.q&&_.we===_.q&&(_.we=window.setTimeout(_.Be,100));return _.p},call:_.Ke,Zt:_.Ze,d:_.Ie,i:_.Je}};
if(!window.gadgets||!window.gadgets.rpc){_.gf=function(a,c){if(!_.bf[a]){var f=_.cf;c||(f=_.df);_.bf[a]=f;for(var g=_.ef[a]||[],h=0;h<g.length;++h){var j=g[h];j.t=_.ff[a];f.call(a,j.f,j)}_.ef[a]=[]}};_.mf=function(a,c,f,g,h){function j(){_.hf=_.p}if(!_.ff[c]||_.ff[c]!==f)(0,_.Ib)("Invalid auth token. "+_.ff[c]+" vs "+f),(0,_.jf)(c,2);h.onunload=function(){_.kf[c]&&!_.hf&&((0,_.jf)(c,1),_.S.Gg(c))};_.lf||("undefined"!=typeof window.addEventListener?window.addEventListener("unload",j,_.v):"undefined"!=
typeof window.attachEvent&&window.attachEvent("onunload",j),_.lf=_.p);g=_.Pb.parse((0,window.decodeURIComponent)(g))};_.pf=function(a,c){if(a&&"string"===typeof a.s&&"string"===typeof a.f&&a.a instanceof window.Array)if(_.ff[a.f]&&_.ff[a.f]!==a.t&&((0,_.Ib)("Invalid auth token. "+_.ff[a.f]+" vs "+a.t),(0,_.jf)(a.f,2)),"__ack"===a.s)window.setTimeout(function(){(0,_.gf)(a.f,_.p)},0);else{a.c&&(a.callback=function(c){_.S.call(a.f,(a.g?"legacy__":"")+"__cb",_.q,a.c,c)});if(c){var f=(0,_.nf)(c);a.origin=
c;var g=a.r;if(!g||(0,_.nf)(g)!=f)g=c;a.referer=g}f=(_.of[a.s]||_.of[""]).apply(a,a.a);a.c&&"undefined"!==typeof f&&_.S.call(a.f,"__cb",_.q,a.c,f)}};_.nf=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);-1==a.indexOf("://")&&(a=window.location.protocol+"//"+a);var c=a.substring(a.indexOf("://")+3),f=c.indexOf("/");-1!=f&&(c=c.substring(0,f));var a=a.substring(0,a.indexOf("://")),f="",g=c.indexOf(":");if(-1!=g){var h=c.substring(g+
1),c=c.substring(0,g);if("http"===a&&"80"!==h||"https"===a&&"443"!==h)f=":"+h}return a+"://"+c+f};_.qf=function(a){if("/"==a.charAt(0)){var c=a.indexOf("|");return{id:0<c?a.substring(1,c):a.substring(1),origin:0<c?a.substring(c+1):_.q}}return _.q};_.rf=function(a){if("undefined"===typeof a||".."===a)return window.parent;var c=(0,_.qf)(a);if(c)return window.top.frames[c.id];a=(0,window.String)(a);return(c=window.frames[a])?c:(c=window.document.getElementById(a))&&c.contentWindow?c.contentWindow:_.q};
_.sf=function(a,c){if(_.kf[a]!==_.p){"undefined"===typeof _.kf[a]&&(_.kf[a]=0);var f=(0,_.rf)(a);(".."===a||f!=_.q)&&_.cf.Pe(a,c)===_.p?_.kf[a]=_.p:_.kf[a]!==_.p&&10>_.kf[a]++?window.setTimeout(function(){(0,_.sf)(a,c)},500):(_.bf[a]=_.df,_.kf[a]=_.p)}};_.uf=function(a){(a=_.tf[a])&&"/"===a.substring(0,1)&&(a="/"===a.substring(1,2)?window.document.location.protocol+a:window.document.location.protocol+"//"+window.document.location.host+a);return a};_.wf=function(a,c,f){c&&!/http(s)?:\/\/.+/.test(c)&&
(0==c.indexOf("//")?c=window.location.protocol+c:"/"==c.charAt(0)?c=window.location.protocol+"//"+window.location.host+c:-1==c.indexOf("://")&&(c=window.location.protocol+"//"+c));_.tf[a]=c;"undefined"!==typeof f&&(_.vf[a]=!!f)};_.xf=function(a,c){c=c||"";_.ff[a]=(0,window.String)(c);(0,_.sf)(a,c)};_.Af=function(a){a=(a.passReferrer||"").split(":",2);_.yf=a[0]||"none";_.zf=a[1]||"origin"};_.Bf=function(a){"true"===(0,window.String)(a.useLegacyProtocol)&&(_.cf=_.Yd.Ej||_.df,_.cf.xa(_.pf,_.gf))};_.Wf=
function(a,c,f){if(".."===a){var g=f||_.Cf.rpctoken||_.Cf.ifpctok||"",a=function(a){a=a&&a.rpc||{};(0,_.Af)(a);var f=a.parentRelayUrl||"",f=(0,_.nf)(_.Cf.parent||c)+f;(0,_.wf)("..",f,"true"===(0,window.String)(a.useLegacyProtocol));(0,_.Bf)(a);(0,_.xf)("..",g)};!_.Cf.parent&&c?a({}):_.Jc.ea("rpc",_.q,a)}else a:{var h=_.q;if("/"!=a.charAt(0)){if(!_.R)break a;(h=window.document.getElementById(a))||(0,_.l)((0,window.Error)("g`"+a))}var h=h&&h.src,j=c||_.S.Va(h);(0,_.wf)(a,j);h=_.R.wa(h);(0,_.xf)(a,f||
h.rpctoken)}};_.of={};_.tf={};_.vf={};_.ff={};_.Xf=0;_.Yf={};_.kf={};_.Cf={};_.bf={};_.ef={};_.yf=_.q;_.zf=_.q;_.Zf=window.top!==window.self;_.$f=window.name;_.jf=(0,_.x)();_.ag=window.console;_.bg=_.ag&&_.ag.log&&function(a){_.ag.log(a)}||(0,_.x)();_.eg=function(a){return function(){(0,_.bg)(a+": call ignored")}};_.df={getCode:(0,_.A)("noop"),isParentVerifiable:(0,_.A)(_.p),init:(0,_.eg)("init"),setup:(0,_.eg)("setup"),call:(0,_.eg)("call")};_.R&&(_.Cf=_.R.wa());_.hf=_.v;_.lf=_.v;_.cf=function(){if("flash"==
_.Cf.rpctx)return _.Yd.lj;if("rmr"==_.Cf.rpctx)return _.Yd.Fr;var a="function"===typeof window.postMessage?_.Yd.zo:"object"===typeof window.postMessage?_.Yd.zo:window.ActiveXObject?_.Yd.lj?_.Yd.lj:_.Yd.Qq?_.Yd.Qq:_.Yd.Ej:0<window.navigator.userAgent.indexOf("WebKit")?_.Yd.Fr:"Gecko"===window.navigator.product?_.Yd.frameElement:_.Yd.Ej;a||(a=_.df);return a}();_.of[""]=function(){(0,_.bg)("Unknown RPC service: "+this.s)};_.of.__cb=function(a,c){var f=_.Yf[a];f&&(delete _.Yf[a],f.call(this,c))};_.S=
{Oa:function(a){"function"===typeof a.Vw&&(_.jf=a.Vw)},ea:function(a,c){("__cb"===a||"__ack"===a)&&(0,_.l)((0,window.Error)("h"));""===a&&(0,_.l)((0,window.Error)("i"));_.of[a]=c},he:function(a){("__cb"===a||"__ack"===a)&&(0,_.l)((0,window.Error)("j"));""===a&&(0,_.l)((0,window.Error)("k"));delete _.of[a]},li:function(a){_.of[""]=a},Bi:function(){delete _.of[""]},xh:(0,_.x)(),call:function(a,c,f,g){var a=a||"..",h="..";".."===a?h=_.$f:"/"==a.charAt(0)&&(h=_.S.Va(window.location.href),h="/"+_.$f+(h?
"|"+h:""));++_.Xf;f&&(_.Yf[_.Xf]=f);var j={s:c,f:h,c:f?_.Xf:0,a:window.Array.prototype.slice.call(arguments,3),t:_.ff[a],l:!!_.vf[a]},m;a:if("bidir"===_.yf||"c2p"===_.yf&&".."===a||"p2c"===_.yf&&".."!==a){m=window.location.href;var o="?";if("query"===_.zf)o="#";else if("hash"===_.zf)break a;o=m.lastIndexOf(o);o=-1===o?m.length:o;m=m.substring(0,o)}else m=_.q;m&&(j.r=m);".."!==a&&(0,_.qf)(a)==_.q&&!window.document.getElementById(a)||(m=_.bf[a],!m&&(0,_.qf)(a)!==_.q&&(m=_.cf),0===c.indexOf("legacy__")&&
(m=_.cf,j.s=c.substring(8),j.c=j.c?j.c:_.Xf),j.g=_.p,j.r=h,m?(_.vf[a]&&(m=_.Yd.Ej),m.call(a,h,j)===_.v&&(_.bf[a]=_.df,_.cf.call(a,h,j))):_.ef[a]?_.ef[a].push(j):_.ef[a]=[j])},Gh:_.uf,Gf:_.wf,Ff:_.xf,Qe:_.Wf,Id:function(a){return _.ff[a]},Gg:function(a){delete _.tf[a];delete _.vf[a];delete _.ff[a];delete _.kf[a];delete _.bf[a]},Fh:function(){return _.cf.Ep()},ji:function(a,c){4<a.length?_.cf.Zt(a,_.pf):_.mf.apply(_.q,a.concat(c))},ki:function(a){a.a=window.Array.prototype.slice.call(a.a);window.setTimeout(function(){(0,_.pf)(a)},
0)},Va:_.nf,Md:function(a){var c=_.q,c=(0,_.uf)(a);c||(c=(c=(0,_.qf)(a))?c.origin:".."==a?_.Cf.parent:window.document.getElementById(a).src);return(0,_.nf)(c)},xa:function(){_.cf.xa(_.pf,_.gf)===_.v&&(_.cf=_.df);_.Zf?(0,_.Wf)(".."):_.Jc.ea("rpc",_.q,function(a){a=a.rpc||{};(0,_.Af)(a);(0,_.Bf)(a)})},Po:_.rf,Yt:_.qf,b:"__ack",Tk:_.$f||"..",p:0,i:1,d:2};_.S.xa()}else if("undefined"==typeof _.S||!_.S)_.S=window.gadgets.rpc,_.S.Oa=_.S.config,_.S.ea=_.S.register,_.S.he=_.S.unregister,_.S.li=_.S.registerDefault,
_.S.Bi=_.S.unregisterDefault,_.S.xh=_.S.forceParentVerifiable,_.S.call=_.S.call,_.S.Gh=_.S.getRelayUrl,_.S.Gf=_.S.setRelayUrl,_.S.Ff=_.S.setAuthToken,_.S.Qe=_.S.setupReceiver,_.S.Id=_.S.getAuthToken,_.S.Gg=_.S.removeReceiver,_.S.Fh=_.S.getRelayChannel,_.S.ji=_.S.receive,_.S.ki=_.S.receiveSameDomain,_.S.Va=_.S.getOrigin,_.S.Md=_.S.getTargetOrigin,_.S.Po=_.S._getTargetWin,_.S.Yt=_.S._parseSiblingId;
(0,_.Q)("gadgets.rpc.config",_.S.Oa);(0,_.Q)("gadgets.rpc.register",_.S.ea);(0,_.Q)("gadgets.rpc.unregister",_.S.he);(0,_.Q)("gadgets.rpc.registerDefault",_.S.li);(0,_.Q)("gadgets.rpc.unregisterDefault",_.S.Bi);(0,_.Q)("gadgets.rpc.forceParentVerifiable",_.S.xh);(0,_.Q)("gadgets.rpc.call",_.S.call);(0,_.Q)("gadgets.rpc.getRelayUrl",_.S.Gh);(0,_.Q)("gadgets.rpc.setRelayUrl",_.S.Gf);(0,_.Q)("gadgets.rpc.setAuthToken",_.S.Ff);(0,_.Q)("gadgets.rpc.setupReceiver",_.S.Qe);
(0,_.Q)("gadgets.rpc.getAuthToken",_.S.Id);(0,_.Q)("gadgets.rpc.removeReceiver",_.S.Gg);(0,_.Q)("gadgets.rpc.getRelayChannel",_.S.Fh);(0,_.Q)("gadgets.rpc.receive",_.S.ji);(0,_.Q)("gadgets.rpc.receiveSameDomain",_.S.ki);(0,_.Q)("gadgets.rpc.getOrigin",_.S.Va);(0,_.Q)("gadgets.rpc.getTargetOrigin",_.S.Md);

}catch(e){_._DumpException(e)}
try{
_.fg=_.Lc=_.Lc||{};_.gg={Bo:"bsh",Eo:"h"};window.___jsl=window.___jsl||{};_.fg.hh={Lu:function(){return window.___jsl[_.gg.Bo]},gm:function(){return window.___jsl[_.gg.Eo]},yk:function(a){window.___jsl[_.gg.Bo]=a},fx:function(a){window.___jsl[_.gg.Eo]=a}};

}catch(e){_._DumpException(e)}
try{
_.hg=window.iframer=window.iframer||{};_.X=window.iframes=window.iframes||{};
}catch(e){_._DumpException(e)}
try{
_.ig=function(a,c,f){var g=(0,window.RegExp)("([#].*&|[#])"+c+"=([^&#]*)","g"),c=(0,window.RegExp)("([?#].*&|[?#])"+c+"=([^&#]*)","g");if(a=a&&(g.exec(a)||c.exec(a)))try{f=(0,window.decodeURIComponent)(a[2])}catch(h){}return f};_.jg=function(a){var c=(0,_.O)("googleapis.config/sessionIndex");c==_.q&&(c=window.__X_GOOG_AUTHUSER);if(c==_.q){var f=window.google;f&&(c=f.authuser)}c==_.q&&(a==_.q&&(a=window.location.href),c=a?(0,_.ig)(a,"authuser")||_.q:_.q);return c==_.q?_.q:(0,window.String)(c)};
_.kg=function(a,c,f){a=(0,window.String)(a);if(((0,_.ig)(a,"authuser")||_.q)!=_.q||((0,_.ig)(a,"hd")||_.q)!=_.q)return a;c=(0,_.jg)(c);if(f){var g=a,h=g.match(/^((https?:)?\/\/[^\/?#]*)?(\/[^\/?#]+)\/[0-9]+([\/][^?#]*)([?#].*)?$/);if(h&&h[0]){var j=h[1],m=h[4],o=h[5];h[3]=="/"+f&&(g=(j||"")+(m||"/")+(o||""))}if((h=g.match(/^(((https?:)?\/\/[^\/?#]*)([\/][^?#]*)?|([\/][^?#]*))([?#].*)?$/))&&h[0])return j=h[2],a=h[4]||h[5],o=h[6],c!=_.q&&(g=(j||"")+"/"+f+"/"+(0,window.encodeURIComponent)(c)+(a||"/")+
(o||"")),g}f=c==_.q?(0,window.encodeURIComponent)("authuser")+"=0":c.match(/^([-a-z0-9]+[.])+[-a-z0-9]+$/)?[(0,window.encodeURIComponent)("authuser")+"=",(0,window.encodeURIComponent)((0,window.String)(c)),"&"+(0,window.encodeURIComponent)("hd")+"=",(0,window.encodeURIComponent)(c)].join(""):["authuser=",(0,window.encodeURIComponent)(c)].join("");a=a.split("#");c=a[0].indexOf("?");0>c?a[0]=[a[0],"?",f].join(""):(g=[a[0]],c<a[0].length-1&&g.push("&"),g.push(f),a[0]=g.join(""));return g=a.join("#")};
_.lg=_.kg;
}catch(e){_._DumpException(e)}
try{
_.mg=function(a){var c=(0,_.ig)(a.location.href,"urlindex");if(c=(0,_.Oa)(_.qb,"fUrl",[])[c]){var f=a.location.hash,c=c+(/#/.test(c)?f.replace(/^#/,"&"):f);a.location.replace(c)}};_.X.R=_.X.R||{};_.X.R.Co="friendlyIframe";_.X.R.nu=function(a){try{return!!a.document}catch(c){}return _.v};_.X.R.Ae=function(a){var c=a.parent;return a!=c&&_.X.R.nu(c)?_.X.R.Ae(c):a};_.X.R.wq=function(a){try{return _.X.R.Ae(a)!=a&&!!a.frameElement&&a.frameElement.name==_.X.R.Co}catch(c){return _.v}};_.X.R.Qv=function(a){var c=a.userAgent||"",a=a.product||"";return 0!=c.indexOf("Opera")&&-1==c.indexOf("WebKit")&&"Gecko"==a&&0<c.indexOf("rv:1.")};
if(window.ToolbarApi)_.ng=window.ToolbarApi,_.ng.Pa=window.ToolbarApi.getInstance,_.ng.prototype=window.ToolbarApi.prototype,_.D=_.ng.prototype,_.D.er=_.ng.prototype.openWindow,_.D.kp=_.ng.prototype.closeWindow,_.D.Ur=_.ng.prototype.setOnCloseHandler,_.D.gp=_.ng.prototype.canClosePopup,_.D.Ar=_.ng.prototype.resizeWindow;else{_.og=_.q;_.ng=(0,_.x)();_.ng.Pa=function(){!_.og&&(window.external&&window.external.GTB_IsToolbar)&&(_.og=new _.ng);return _.og};_.D=_.ng.prototype;_.D.er=function(a){return window.external.GTB_OpenPopup&&
window.external.GTB_OpenPopup(a)};_.D.kp=function(a){window.external.GTB_ClosePopupWindow&&window.external.GTB_ClosePopupWindow(a)};_.D.Ur=function(a,c){window.external.GTB_SetOnCloseHandler&&window.external.GTB_SetOnCloseHandler(a,c)};_.D.gp=function(a){return window.external.GTB_CanClosePopup&&window.external.GTB_CanClosePopup(a)};_.D.Ar=function(a,c){return window.external.GTB_ResizeWindow&&window.external.GTB_ResizeWindow(a,c)};window.ToolbarApi=_.ng;window.ToolbarApi.getInstance=_.ng.Pa};
if(!window.iframes||!window.iframes.open){_.qg=/^[-_.0-9A-Za-z]+$/;_.rg={open:"open",onready:"ready",close:"close",onresize:"resize",onOpen:"open",onReady:"ready",onClose:"close",onResize:"resize",onRenderStart:"renderstart"};_.sg={onBeforeParentOpen:"beforeparentopen"};_.tg={longdesc:_.p,name:_.p,src:_.p,frameborder:_.p,marginwidth:_.p,marginheight:_.p,scrolling:_.p,align:_.p,height:_.p,width:_.p,id:_.p,"class":_.p,style:_.p,title:_.p,tabindex:_.p,hspace:_.p,vspace:_.p,allowtransparency:_.p};_.ug=
{onOpen:function(a){var c=a.Ha();a.Tb(c.container||c.element);return a},onClose:function(a){a.remove()}};_.vg=window.encodeURIComponent||window.escape;_.wg=function(a){(0,_.Ib)(a.join(""))};_.xg=function(){_.X.tq++;return["I",_.X.tq,"_",(new window.Date).getTime()].join("")};_.yg=function(a){var c={allowtransparency:"true",frameborder:0,hspace:0,marginheight:0,marginwidth:0,scrolling:"no",style:"",tabindex:"0",vspace:0,width:"100%"},f;for(f in a)a.hasOwnProperty(f)&&(c[f]=a[f]);return c};_.Zg=function(a,
c,f){f=f||{};f.id||(f.id=a);f.name||(f.name=a);f.src||(f.src=c);a=(0,_.yg)(f);c=[];c.push("<iframe ");for(var g in a)a.hasOwnProperty(g)&&(_.tg[g.toLowerCase()]?(f=(0,window.String)(a[g]),c.push(g),c.push('="'),c.push(_.R.uh("style"==g.toLowerCase()?(0,_.zg)(f):f)),c.push('" ')):(0,_.wg)(['Iframe attribute "',g,'" not allowed.']));c.push("></iframe>");return c.join("")};_.zg=function(a){if(!a)return"";for(var c=[],a=a.split(";"),f=0,g=a.length;f<g;++f){var h=a[f];0==h.length&&f+1==g||(h=h.split(":"),
2==h.length&&h[0].match(/^[ a-zA-Z_-]+$/)&&h[1].match(/^[ +.%0-9a-zA-Z_-]+$/)?c.push(h.join(":")):(0,_.wg)(['Iframe style "',a[f],'" not allowed.']))}return c.join(";")};_.$g=function(a){if(0==a.indexOf("http:")||0==a.indexOf("https:")||0==a.indexOf("javascript:"))return a;if(0==a.indexOf("//"))return window.location.protocol+a;if(0==a.indexOf("/"))return window.location.protocol+"//"+window.location.host+a;var c=window.location.protocol+"//"+window.location.host+window.location.pathname,f=c.lastIndexOf("/");
return c.substring(0,f+1)+a};_.ah=function(a){return a instanceof window.Array?a.join(","):a instanceof window.Object?_.Pb.stringify(a):a};_.bh=function(a,c,f){var g={},h=a.indexOf("#");-1==h?(g.hash=_.q,g.ne=a):(g.hash=a.substring(h+1),g.ne=a.substring(0,h));a=g.ne.indexOf("?");-1==a?g.Xc=_.q:(g.Xc=g.ne.substring(a+1),g.ne=g.ne.substring(0,a));var a=f?g.hash?[g.hash]:[]:g.Xc?[g.Xc]:[],j;for(j in c)c.hasOwnProperty(j)&&(h=(0,_.ah)(c[j]),a.push([(0,_.vg)(j),(0,_.vg)(h)].join("=")));f?g.hash=a.join("&"):
g.Xc=a.join("&");return g.ne+(g.Xc?"?"+g.Xc:"")+(g.hash?"#"+g.hash:"")};_.ch=(0,_.x)();_.fh=function(){var a=(0,_.jg)(_.n);return a!==_.n&&a!==_.q&&""!==a?"u/"+a+"/":""};_.gh=function(a){var c=_.R.wa().jsh||_.Lc.hh.gm();!a.jsh&&c&&(a.jsh=c);c=_.R.wa()._bsh||_.Lc.hh.Lu();!a._bsh&&c&&(a._bsh=c)};_.hh=function(a){a&&a.match(_.qg)&&(0,_.kb)("googleapis.config/gcv",a)};_.ih=function(a){_.Lc.hh.fx(a)};_.jh=function(a){_.Lc.hh.yk(a)};_.kh=function(a,c){var f=c||{},g;for(g in a)a.hasOwnProperty(g)&&(f[g]=
a[g]);return f};_.lh=function(a){_.X.qk[a]||(_.X.qk[a]={},_.S.ea(a,function(c,f){var g=this.f;if("string"==typeof c&&!(c in{})&&!(g in{})){var h=this.callback,j=_.X.qk[a][g],m;j&&window.Object.hasOwnProperty.call(j,c)?m=j[c]:window.Object.hasOwnProperty.call(_.X.ig,a)&&(m=_.X.ig[a]);if(m)return g=window.Array.prototype.slice.call(arguments,1),m._iframe_wrapped_rpc_&&h&&g.push(h),m.apply({},g)}(0,_.wg)(['Unregistered call in window "',window.name,'" for method "',a,'", via proxyId "',c,'" from frame "',
g,'".']);return _.q}));return _.X.qk[a]};_.mh=function(a,c,f,g,h){var j=[],m;for(m in a)if(a.hasOwnProperty(m)){var o=c,t=f,u=a[m],w=g,C=(0,_.lh)(m);C[o]=C[o]||{};w=_.R.xg(w,u);u._iframe_wrapped_rpc_&&(w._iframe_wrapped_rpc_=_.p);C[o][t]=w;j.push(m)}if(h)for(m in _.X.ig)_.X.ig.hasOwnProperty(m)&&j.push(m);return j.join(",")};_.nh=function(a,c,f){function g(g){var j=window.Array.prototype.slice.call(arguments,0),m=j[j.length-1];if("function"===typeof m){var o=m;j.pop()}j.unshift(c,a,o,f);var t;a:if(".."==
c||window.document.getElementById(c))t=window;else{for(m=0;m<_.X.Zl.length;m++)try{var u=_.X.Zl[m];if(u&&u.document&&(u.document||window.document).getElementById(c)){t=u;break a}}catch(w){}t=_.q}t?t==window?_.S.call.apply(_.S,j):(t=t.gadgets.rpc,t.call.apply(t,j)):(0,_.wg)(["RPC ",a,' not sent: target iframe "',c,'" not found.'])}g._iframe_wrapped_rpc_=_.p;return g};_.oh=function(a,c,f){var g={};if(a&&a._methods)for(var a=a._methods.split(","),h=0;h<a.length;h++){var j=a[h];g[j]=(0,_.nh)(j,c,f)}return g};
_.ph=function(a){return a&&a.disableMultiLevelParentRelay?_.v:_.hg&&_.hg._open&&"inline"!=a.style&&a.inline!==_.p&&!(a.container&&("string"==typeof a.container&&window.document.getElementById(a.container)||window.document==(a.container.ownerDocument||a.container.document)))};_.qh=function(a){a&&a.parentNode&&a.parentNode.removeChild(a)};_.rh=function(a,c){function f(){}f.prototype=c.prototype;a.prototype=new f};_.sh=function(a,c,f,g,h,j,m,o){if(":"==a.charAt(0)){var a="iframes/"+a.substring(1),t=
a+"/params",u={},w=(0,_.O)(t);(0,_.kb)(t,w||u);t=a+"/url";u=(u=(0,_.O)(a+"/url"))||"";u=u.replace(/:session_prefix:/g,(0,_.fh)());u=u.replace(/:session_index:/g,(0,_.jg)(_.n)||"0");u=u.replace(/:socialhost:/g,(0,_.O)("iframes/:socialhost:"));(0,_.kb)(t,(0,_.$g)(u));a=(0,_.O)(a)}else a={url:(0,_.$g)(a)};this.Oa=a;this.openParams=this.i=c;this.tb=f||{};this.nc=g;this.p=_.v;this.ew(c.style);this.d={};this.Df(function(){this.bu(h);j&&this.bl("close",j)});this.Wd=this.ac=m;this.An=(o||[]).slice();m&&this.An.unshift(m.ka())};
_.D=_.sh.prototype;_.D.Ha=(0,_.z)("i");_.D.Xb=(0,_.z)("tb");_.D.Jd=(0,_.z)("nc");_.D.ob=(0,_.z)("Wd");_.D.ew=function(a){if(!this.p)if(a=a&&!_.X.vi[a]&&_.X.Hl[a]){this.B=[];var c=this;a(function(){c.p=_.p;for(var a=0,g=c.B.length;a<g;++a)c.B[a].call(c)})}else this.p=_.p};_.D.Df=function(a){this.p?a.call(this):this.B.push(a)};_.D.bu=function(a){var c=this.Tu();if(c){if("function"===typeof c)c=c(this);else{var f={},g;for(g in c){var h=c[g];f[g]="function"===typeof h?_.R.xg(c,h,this):h}c=f}for(var j in a)f=
c[j],"function"===typeof f&&this.bl(a[j],_.R.xg(c,f))}};_.D.Ca=function(a,c){this.Df(function(){this.bl(a,c)})};_.D.bl=function(a,c){this.d[a]=this.d[a]||[];this.d[a].push(c)};_.D.qd=function(a,c){this.Df(function(){var f=this.d[a];if(f)for(var g=0,h=f.length;g<h;++g)if(f[g]===c){f.splice(g,1);break}})};_.D.Rc=function(a,c){var f,g=this.d[a];if(g)for(var h=window.Array.prototype.slice.call(arguments,1),j=0,m=g.length;j<m;++j)try{f=g[j].apply({},h)}catch(o){(0,_.wg)(['Exception when calling callback "',
a,'" with exception "',o.name,": ",o.message,'".'])}return f};_.D.Tu=function(){var a=this.i.style;return a&&_.X.vi[a]?_.X.vi[a]:a?((0,_.bc)(['Missing handler for style "',a,'". Continuing with default handler.'].join("")),_.q):_.ug};_.D.uj=function(a){return"number"==typeof a?{value:a,hf:a+"px"}:"100%"==a?{value:100,hf:"100%",Eq:_.p}:_.q};_.D.rs=function(){return(0,_.bh)(this.Oa.url,this.tb,_.v)};_.th=function(a,c,f,g,h,j,m){_.sh.call(this,a,c,f,g,_.rg,h,j,m);this.id=c.id||(0,_.xg)();this.Bx=!!c.rpcToken;
this.Tn=c.rpcToken||window.Math.round(1E9*(0,_.uc)());var a=this.tb,c={},f=this.Oa.params||{},o;for(o in a)"#"==o.charAt(0)&&(c[o.substring(1)]=a[o]),0==o.indexOf("fr-")&&(c[o.substring(3)]=a[o]),"#"==f[o]&&(c[o]=a[o]);for(var t in c)delete a["fr-"+t],delete a["#"+t],delete a[t];this.Rv=c;this.Rl={};this.Df(function(){this.Rc("open");(0,_.kh)(this.Rl,this)})};(0,_.rh)(_.th,_.sh);_.D=_.th.prototype;_.D.Tb=function(a,c){if(!this.Oa.url)return(0,_.wg)(["Cannot open iframe, empty URL."]),this;var f=window.location.protocol+
"//"+window.location.host,g=this.id;(0,_.gh)(this.tb);var h=(0,_.kh)(this.nc);h._ready=this.ek;h._close=this.close;h._open=this.fr;h._resizeMe=this.Br;h._renderstart=this.ar;var j=this.Rv;j.id=g;j.parent=f;j.rpctoken=this.Tn;j._methods=(0,_.mh)(h,g,"",this,_.p);f=this.rs();f=(0,_.bh)(f,j,_.p);a="string"===typeof a?window.document.getElementById(a):a;if(this.Ha().allowPost&&2E3<f.length)this.Bw(a,g,j,c);else if(this.Bx)a.innerHTML=(0,_.Zg)(g,f,c);else if(_.X.R.Qv(window.navigator||{})){a.innerHTML=
(0,_.Zg)(g,"about:blank",c);a.firstChild.src=f;try{a.firstChild.contentDocument.location.href=f}catch(m){}}else{j=(0,_.Zg)(g,f,c);try{a.innerHTML=j}catch(o){h=window.document.createElement("div");for(h.innerHTML=j;a.firstChild;)a.removeChild(a.firstChild);a.appendChild(h.firstChild)}}this.cf=a;this.Sc=a.firstChild;_.X.tf[g]=this;_.S.Ff(g,this.Tn);_.S.Gf(g,f);return this};_.D.ju=function(a){var c=a.id,f=a.src,g=/#(?:.*&)?rpctoken=(\d+)/.exec(f),g=g&&g[1];this.id=c;this.Tn=g;this.cf=a.parentNode;this.Sc=
a;_.X.tf[c]=this;a=(0,_.kh)(this.nc);a._ready=this.ek;a._close=this.close;a._open=this.fr;a._resizeMe=this.Br;a._renderstart=this.ar;(0,_.mh)(a,c,"",this,_.p);_.S.Ff(c,g);_.S.Gf(c,f);return this};_.D.hu=function(a){var a=(0,_.yg)(a||{}),c;for(c in a)window.Object.prototype.hasOwnProperty.call(a,c)&&("style"==c?this.Sc.style.cssText=a[c]:this.Sc.setAttribute(c,a[c]))};_.D.Bw=function(a,c,f,g){a.innerHTML=(0,_.Zg)(c,"",g);var h;-1!=window.navigator.userAgent.indexOf("WebKit")&&(h=a.firstChild,g=(0,_.Zg)(c+
"_inner","",{style:"display:none"}),h=h.contentWindow.document,h.open(),h.write(g));g=(0,_.bh)(this.Oa.url,f,_.p);f=this.tb||{};g={action:g,method:"POST",target:c};c=window.document.createElement("form");c.style.display="none";for(var j in g)g.hasOwnProperty(j)&&(c[j]=g[j]);for(var m in f)f.hasOwnProperty(m)&&(j=window.document.createElement("input"),j.type="hidden",j.name=m,j.value=f[m],c.appendChild(j));a.appendChild(c);c.submit();c.parentNode.removeChild(c);h&&h.close()};_.D.jc=function(a,c){this.Rl[a]=
c};_.D.ka=(0,_.z)("id");_.D.La=(0,_.z)("Sc");_.D.na=(0,_.z)("cf");_.D.vd=(0,_.da)("cf");_.D.ek=function(a){var c=(0,_.oh)(a,this.id,"");this.Wd&&"function"==typeof this.nc._ready&&(a._methods=(0,_.mh)(c,this.Wd.ka(),this.id,this,_.v),this.nc._ready(a));(0,_.kh)(a,this);(0,_.kh)(c,this);this.Rc("ready",a)};_.D.ar=function(a){this.Rc("renderstart",a)};_.D.Iw=function(a,c,f){f._methods=(0,_.mh)((0,_.oh)(f,a,""),this.id,a,this,_.v);c(f)};_.D.close=function(a){a=this.Rc("close",a);if(_.X.R.wq(window)){var c=
window.frameElement,f=c.parentNode;"friendlyIframeContainer"==f.className?(0,_.qh)(f):(0,_.qh)(c)}delete _.X.tf[this.id];return a};_.D.remove=function(){(0,_.qh)(window.document.getElementById(this.id))};_.D.fr=function(a){var c=(0,_.oh)(a.params,this.id,a.proxyId);delete a.params._methods;"_parent"==a.openParams.anchor&&(a.openParams.anchor=this.cf);if((0,_.ph)(a.openParams))new _.uh(a.url,a.openParams,a.params,c,c._onclose,this,a.openedByProxyChain);else if("expandable"===a.openParams.style&&a.openParams.inline!==
_.p&&_.X.R.Ae(window)!=window)this.Aw(a,c);else{var f=new _.th(a.url,a.openParams,a.params,c,c._onclose,this,a.openedByProxyChain),g=this;f.Df(function(){var a=g.ep(f);c._onopen(a)})}};_.D.Aw=function(a,c){var f=_.X.R.Ae(window),g={height:0,name:_.X.R.Co,style:"left:0;position:absolute;top:0;z-index:-10000",width:0},h=f.document.createElement("ins");h.className="friendlyIframeContainer";h.innerHTML=(0,_.Zg)("","about:blank",g);f.document.body.appendChild(h);f=h.firstChild.contentWindow;_.X.Zl.push(f);
g=f.document;h=['<html><body><script src="',_.X.dm(),'"><\/script></body></html>'].join("");g.open();g.write(h);g.close();g=a.openParams.id||(0,_.xg)();a.openParams.id=g;g=_.R.xg(this,this.Iw,g,c._ready);c._ready=g;var j=_.R.xg(f,function(f,g){if(!f.Ph||"function"!=typeof f.Ph.open)return _.v;var h=f.Ph.open(a.url,a.openParams,a.params,c,c._onclose,g),h=g.ep(h);c._onopen(h);return _.p},f,this),m=window.setInterval(function(){j()&&window.clearInterval(m)},10)};_.D.ep=function(a){var c={childId:a.ka()},
f=a.Rl;f._toclose=a.close;c._methods=(0,_.mh)(f,this.id,a.id,a,_.v);return c};_.D.Br=function(a){if(this.Rc("resize",a)===_.n&&this.Sc){var c=this.uj(a.width);c!=_.q&&(this.Sc.style.width=c.hf);a=this.uj(a.height);a!=_.q&&(this.Sc.style.height=a.hf);if(this.Sc.parentElement&&(c!=_.q&&c.Eq||a!=_.q&&a.Eq))this.Sc.parentElement.style.display="block"}};_.uh=function(a,c,f,g,h,j,m){_.sh.call(this,a,c,f,g,_.sg,h,j,m);this.url=a;this.b=_.q;this.Q=(0,_.xg)();this.Df(function(){this.Rc("beforeparentopen");
var a=(0,_.kh)(this.nc);a._onopen=this.$;a._ready=this.ek;a._onclose=this.M;this.tb._methods=(0,_.mh)(a,"..",this.Q,this,_.p);var a={},c;for(c in this.tb)a[c]=(0,_.ah)(this.tb[c]);var f=this.Oa.url;if(this.i.hideUrlFromParent){c=window.name;var g=f,f=this.rs(),h=a,a={};a._methods=h._methods;a["#opener"]=h["#opener"];a["#urlindex"]=h["#urlindex"];a["#opener"]&&h["#urlindex"]!=_.n?(a["#opener"]=c+","+a["#opener"],c={url:g,tb:a}):(g=(0,_.Oa)(_.qb,"fUrl",[]),h=g.length,g[h]=f,_.qb.rUrl=_.mg,a["#opener"]=
c,a["#urlindex"]=h,c=_.Lc.Va(_.wb.location.href),f=(0,_.O)("iframes/relay_url_"+(0,window.encodeURIComponent)(c))||"/_/gapi/sibling/1/frame.html",c={url:c+f,tb:a});f=c.url;a=c.tb}_.hg._open({url:f,openParams:this.i,params:a,proxyId:this.Q,openedByProxyChain:this.An})})};(0,_.rh)(_.uh,_.sh);_.uh.prototype.Jp=(0,_.z)("b");_.uh.prototype.$=function(a){this.b=a.childId;var c=(0,_.oh)(a,"..",this.b);(0,_.kh)(c,this);this.close=c._toclose;_.X.tf[this.b]=this;this.Wd&&this.nc._onopen&&(a._methods=(0,_.mh)(c,
this.Wd.ka(),this.b,this,_.v),this.nc._onopen(a))};_.uh.prototype.ek=function(a){var c=(0,window.String)(this.b),f=(0,_.oh)(a,"..",c);(0,_.kh)(a,this);(0,_.kh)(f,this);this.Rc("ready",a);this.Wd&&this.nc._ready&&(a._methods=(0,_.mh)(f,this.Wd.ka(),c,this,_.v),this.nc._ready(a))};_.uh.prototype.M=function(a){if(this.Wd&&this.nc._onclose)this.nc._onclose(a);else return a=this.Rc("close",a),delete _.X.tf[this.b],a};_.vh=function(a,c,f,g,h,j,m){_.sh.call(this,a,c,f,g,_.sg,j,m);this.ia=h;g._close=this.close;
this.onClosed=this.b;this.K=0;this.Df(function(){this.Rc("beforeparentopen");var a=(0,_.kh)(this.nc);this.tb._methods=(0,_.mh)(a,"..",this.Q,this,_.p);(0,_.gh)(this.tb);var a=(0,_.bh)(this.Oa.url,this.tb,_.v),c=h.er(a);this.canAutoClose=function(a){a(h.gp(c))};h.Ur(c,this);this.K=c})};(0,_.rh)(_.vh,_.sh);_.vh.prototype.close=function(a){a=this.Rc("close",a);this.ia.kp(this.K);return a};_.vh.prototype.b=function(){this.Rc("close")};_.wh=function(a){return _.X.vi[a]};_.xh=function(a,c){_.X.vi[a]=c};
_.yh=function(a){a=a||{};"auto"===a.height&&(a.height=_.ic.em());var c=window&&_.ng&&_.ng.Pa();c?c.Ar(a.width||0,a.height||0):_.hg&&_.hg._resizeMe&&_.hg._resizeMe(a)};_.zh=function(a){(0,_.hh)(a)};_.pg=function(){function a(a){var c=_.v;try{if(a!=_.q)var f=window.parent.frames[a.id],c=f.iframer.id==a.id&&f.iframes.openedId_(_.hg.id)}catch(m){}try{_.X.jk={origin:this.origin,referer:this.referer,claimedOpenerId:a&&a.id,claimedOpenerProxyChain:a&&a.proxyChain||[],sameOrigin:c};for(a=0;a<_.X.ik.length;++a)_.X.ik[a](_.X.jk);
_.X.ik=[]}catch(o){}}_.X.tf={};_.X.vi={};_.X.Hl={};_.X.tq=0;_.X.Zl=[];_.X.qk={};_.X.ig={};_.X.jk=_.q;_.X.ik=[];_.S.ea("_noop_echo",function(){var a=_.X.tf[this.f],c=a&&a.Wd,f=_.q;c&&(f={},f.id=c.ka(),f.proxyChain=a.An);this.callback(f)});if(window.parent!=window){var c=_.R.wa();c.gcv&&(0,_.hh)(c.gcv);var f=c.jsh;f&&(0,_.ih)(f);(0,_.kh)((0,_.oh)(c,"..",""),_.hg);(0,_.kh)(c,_.hg);window.setTimeout(function(){_.S.call("..","_noop_echo",a)},0)}_.X.Ga=_.wh;_.X.Sa=_.xh;_.X.Qr=_.zh;_.X.ae=_.yh;_.X.Fp=function(a){return _.X.Hl[a]};
_.X.zk=function(a,c){_.X.Hl[a]=c};_.X.zr=_.yh;_.X.$r=_.zh;_.X.Ia={};_.X.Ia.get=_.wh;_.X.Ia.set=_.xh;_.X.So=function(a,c){(0,_.lh)(a);_.X.ig[a]=c||window[a]};_.X.xy=function(a){delete _.X.ig[a]};_.X.open=function(a,c,f,m,o,t){3==arguments.length?m={}:4==arguments.length&&"function"===typeof m&&(o=m,m={});var u="bubble"===c.style&&_.ng&&_.ng.Pa();return u?new _.vh(a,c,f,m,u,o,t):(0,_.ph)(c)?new _.uh(a,c,f,m,o,t):new _.th(a,c,f,m,o,t)};_.X.close=function(a,c){_.hg&&_.hg._close&&_.hg._close(a,c)};_.X.pd=
function(a,c,f){2==arguments.length&&"function"===typeof o&&(f=c,c={});var m=a||{};"height"in m||(m.height=_.ic.em());var o=c||{};m._methods=(0,_.mh)(o,"..","",_.hg,_.p);_.hg&&_.hg._ready&&_.hg._ready(m,f)};_.X.mm=function(a){_.X.jk?a(_.X.jk):_.X.ik.push(a)};_.X.fp=function(a,c,f){var m=window.Array.prototype.slice.call(arguments);_.X.mm(function(a){a.sameOrigin&&(m.unshift("/"+a.claimedOpenerId+"|"+window.location.protocol+"//"+window.location.host),_.S.call.apply(_.S,m))})};_.X.gr=function(a){return!!_.X.tf[a]};
_.X.dm=function(){return["https://ssl.gstatic.com/gb/js/",(0,_.O)("googleapis.config/gcv")].join("")};_.X.qr=function(a){var c={mouseover:1,mouseout:1};if(_.hg._event)for(var f=0;f<a.length;f++){var m=a[f];m in c&&_.R.fh(window.document,m,function(a){_.hg._event({event:a.type,timestamp:(new window.Date).getTime()})},_.p)}};_.X.Sr=_.ih;_.X.yk=_.jh;_.X.fw=_.ch;_.X.vq=_.hg};(0,_.pg)()}else _.X.So=_.X.allow,_.X.fp=_.X.callSiblingOpener,_.X.close=_.X.close,_.X.dm=_.X.getGoogleConnectJsUri,_.X.Ga=_.X.getHandler,
_.X.Fp=_.X.getDeferredHandler,_.X.mm=_.X.getParentInfo,_.X.vq=_.X.iframer,_.X.open=_.X.open,_.X.gr=_.X.openedId_,_.X.qr=_.X.propagate,_.X.pd=_.X.ready,_.X.ae=_.X.resize,_.X.Qr=_.X.setGoogleConnectJsVersion,_.X.Sr=_.X.setJsHint,_.X.yk=_.X.setBootstrapHint,_.X.Sa=_.X.setHandler,_.X.zk=_.X.setDeferredHandler,_.sh=window.IframeBase,_.sh.prototype=window.IframeBase.prototype,_.D=_.sh.prototype,_.D.Ca=_.sh.prototype.addCallback,_.D.Jd=_.sh.prototype.getMethods,_.D.ob=_.sh.prototype.getOpenerIframe,_.D.Ha=
_.sh.prototype.getOpenParams,_.D.Xb=_.sh.prototype.getParams,_.D.qd=_.sh.prototype.removeCallback,_.th=window.Iframe,_.th.prototype=window.Iframe.prototype,_.D=_.th.prototype,_.D.close=_.th.prototype.close,_.D.jc=_.th.prototype.exposeMethod,_.D.ka=_.th.prototype.getId,_.D.La=_.th.prototype.getIframeEl,_.D.na=_.th.prototype.getSiteEl,_.D.Tb=_.th.prototype.openInto,_.D.remove=_.th.prototype.remove,_.D.vd=_.th.prototype.setSiteEl,_.D.Ca=_.th.prototype.addCallback,_.D.Jd=_.th.prototype.getMethods,_.D.ob=
_.th.prototype.getOpenerIframe,_.D.Ha=_.th.prototype.getOpenParams,_.D.Xb=_.th.prototype.getParams,_.D.qd=_.th.prototype.removeCallback,_.uh=window.IframeProxy,_.uh.prototype=window.IframeProxy.prototype,_.D=_.uh.prototype,_.D.Jp=_.uh.prototype.getTargetIframeId,_.D.Ca=_.uh.prototype.addCallback,_.D.Jd=_.uh.prototype.getMethods,_.D.ob=_.uh.prototype.getOpenerIframe,_.D.Ha=_.uh.prototype.getOpenParams,_.D.Xb=_.uh.prototype.getParams,_.D.qd=_.uh.prototype.removeCallback,window.IframeWindow&&(_.vh=window.IframeWindow,
_.vh.prototype=window.IframeWindow.prototype,_.vh.prototype.close=_.vh.prototype.close,_.vh.prototype.b=_.vh.prototype.onClosed),_.X.Ia=window.iframes.handlers,_.X.Ia.get=_.X.Ia.get,_.X.Ia.set=_.X.Ia.set,_.X.zr=_.X.resizeMe,_.X.$r=_.X.setVersionOverride;
(0,_.Q)("iframes.allow",_.X.So);(0,_.Q)("iframes.callSiblingOpener",_.X.fp);(0,_.Q)("iframes.close",_.X.close);(0,_.Q)("iframes.getGoogleConnectJsUri",_.X.dm);(0,_.Q)("iframes.getHandler",_.X.Ga);(0,_.Q)("iframes.getDeferredHandler",_.X.Fp);(0,_.Q)("iframes.getParentInfo",_.X.mm);(0,_.Q)("iframes.iframer",_.X.vq);(0,_.Q)("iframes.open",_.X.open);(0,_.Q)("iframes.openedId_",_.X.gr);(0,_.Q)("iframes.propagate",_.X.qr);(0,_.Q)("iframes.ready",_.X.pd);(0,_.Q)("iframes.resize",_.X.ae);
(0,_.Q)("iframes.setGoogleConnectJsVersion",_.X.Qr);(0,_.Q)("iframes.setBootstrapHint",_.X.yk);(0,_.Q)("iframes.setJsHint",_.X.Sr);(0,_.Q)("iframes.setHandler",_.X.Sa);(0,_.Q)("iframes.setDeferredHandler",_.X.zk);(0,_.Q)("IframeBase",_.sh);(0,_.Q)("IframeBase.prototype.addCallback",_.sh.prototype.Ca);(0,_.Q)("IframeBase.prototype.getMethods",_.sh.prototype.Jd);(0,_.Q)("IframeBase.prototype.getOpenerIframe",_.sh.prototype.ob);(0,_.Q)("IframeBase.prototype.getOpenParams",_.sh.prototype.Ha);
(0,_.Q)("IframeBase.prototype.getParams",_.sh.prototype.Xb);(0,_.Q)("IframeBase.prototype.removeCallback",_.sh.prototype.qd);(0,_.Q)("Iframe",_.th);(0,_.Q)("Iframe.prototype.close",_.th.prototype.close);(0,_.Q)("Iframe.prototype.exposeMethod",_.th.prototype.jc);(0,_.Q)("Iframe.prototype.getId",_.th.prototype.ka);(0,_.Q)("Iframe.prototype.getIframeEl",_.th.prototype.La);(0,_.Q)("Iframe.prototype.getSiteEl",_.th.prototype.na);(0,_.Q)("Iframe.prototype.openInto",_.th.prototype.Tb);
(0,_.Q)("Iframe.prototype.remove",_.th.prototype.remove);(0,_.Q)("Iframe.prototype.setSiteEl",_.th.prototype.vd);(0,_.Q)("Iframe.prototype.addCallback",_.th.prototype.Ca);(0,_.Q)("Iframe.prototype.getMethods",_.th.prototype.Jd);(0,_.Q)("Iframe.prototype.getOpenerIframe",_.th.prototype.ob);(0,_.Q)("Iframe.prototype.getOpenParams",_.th.prototype.Ha);(0,_.Q)("Iframe.prototype.getParams",_.th.prototype.Xb);(0,_.Q)("Iframe.prototype.removeCallback",_.th.prototype.qd);(0,_.Q)("IframeProxy",_.uh);
(0,_.Q)("IframeProxy.prototype.getTargetIframeId",_.uh.prototype.Jp);(0,_.Q)("IframeProxy.prototype.addCallback",_.uh.prototype.Ca);(0,_.Q)("IframeProxy.prototype.getMethods",_.uh.prototype.Jd);(0,_.Q)("IframeProxy.prototype.getOpenerIframe",_.uh.prototype.ob);(0,_.Q)("IframeProxy.prototype.getOpenParams",_.uh.prototype.Ha);(0,_.Q)("IframeProxy.prototype.getParams",_.uh.prototype.Xb);(0,_.Q)("IframeProxy.prototype.removeCallback",_.uh.prototype.qd);(0,_.Q)("IframeWindow",_.vh);
(0,_.Q)("IframeWindow.prototype.close",_.vh.prototype.close);(0,_.Q)("IframeWindow.prototype.onClosed",_.vh.prototype.b);(0,_.Q)("iframes.util.getTopMostAccessibleWindow",_.X.R.Ae);(0,_.Q)("iframes.handlers.get",_.X.Ia.get);(0,_.Q)("iframes.handlers.set",_.X.Ia.set);(0,_.Q)("iframes.resizeMe",_.X.zr);(0,_.Q)("iframes.setVersionOverride",_.X.$r);

}catch(e){_._DumpException(e)}
try{
_.Ah=function(a){a=a.style;a.textIndent="0";a.margin="0";a.padding="0";a.background="transparent";a.borderStyle="none";a.cssFloat="none";a.styleFloat="none";a.lineHeight="normal";a.fontSize="1px";a.verticalAlign="baseline"};_.Bh=function(a){var c=a.clientWidth;return"position:absolute;top:-10000px;width:"+(c?c+"px":a.style.width||"300px")+";margin:0px;border-style:none;"};
_.Ch=function(a,c){var f={};f.width=c?c.width:a.width;f.height=c?c.height:a.height;var g=a.La(),h=g.parentNode,j=f.width,f=f.height;(0,_.Ah)(h);h.style.display="inline-block";g=g.style;g.position="static";g.left=0;g.top=0;g.visibility="visible";j&&(g.width=j+"px");f&&(g.height=f+"px");(j=c?c.title:_.q)&&a.La().setAttribute("title",j)};
_.Dh={open:function(a){var c=window.document.getElementById(a.Ha().container);return a.Tb(c,{style:(0,_.Bh)(c,a)})},attach:function(a,c){var f=window.document.getElementById(a.Ha().container);a.ju(c);a.hu({style:(0,_.Bh)(f,a)})}};_.Dh.onready=_.Ch;_.Dh.onRenderStart=_.Ch;_.Dh.close=function(a){var c=a.na();c&&c.removeChild(a.La())};_.X.Sa("inline",_.Dh);

}catch(e){_._DumpException(e)}
try{

}catch(e){_._DumpException(e)}
try{
_.Eh=function(a,c){this.b=a;this.ue=c};_.Fh=function(a){this.w=this.Cd=a;this.n=_.q;this.slf=0;this.ssh=_.v;this.sen=_.p;this.shl=this.itm=_.q};_.Eh.prototype.p=function(a){this.b.or(this.ue,a)};_.Eh.prototype.ia=function(){this.b.oc(this.ue)};_.Fh.prototype.sm=function(a,c){this.Cd.Or(new _.Eh(a,this));this.n=c};_.Fh.prototype.sh=function(){this.Cd.show()};_.Fh.prototype.hi=function(){this.Cd.oq()};_.Fh.prototype.cl=function(){this.Cd.close()};_.Fh.prototype.en=function(){this.Cd.enable()};_.Fh.prototype.di=function(){this.Cd.disable()};_.Fh.prototype.hl=function(a){this.Cd.Uu(a)};_.Fh.prototype.vr=function(a,c){this.Cd.Lp(a,c)};

}catch(e){_._DumpException(e)}
try{

}catch(e){_._DumpException(e)}
try{
_.Gh=function(a){this.ue=a;this.Sb=0;this.ti=_.v;this.rp=_.p;this.wi=_.q};_.Hh=function(a){return 5==a.Sb||4==a.Sb};
_.Ih=function(a,c,f){this.d=a||{};this.i=c||0;this.p=f||0;a={};c=(0,_.G)(this.bm,this);a.fc=c;c=(0,_.G)(this.pk,this);a.rc=c;c=(0,_.G)(this.Ck,this);a.sc=c;c=(0,_.G)(this.Oh,this);a.hc=c;c=(0,_.G)(this.jh,this);a.cc=c;c=(0,_.G)(this.iq,this);a.os=c;c=(0,_.G)(this.hq,this);a.or=c;c=(0,_.G)(this.fq,this);a.oh=c;c=(0,_.G)(this.dq,this);a.oc=c;c=(0,_.G)(this.eq,this);a.oe=c;c=(0,_.G)(this.gq,this);a.oi=c;this.b=a};
_.Jh=function(a,c){var f=a.p-a.i;0<f&&(f=(0,window.setTimeout)((0,_.G)(function(){(0,_.Hh)(c)||(c.Sb=4,this.jh(c.xe()))},a),f),c.wi=f)};_.Yh=function(a,c){c.wi!=_.q&&((0,window.clearTimeout)(c.wi),c.wi=_.q)};_.Zh=function(a,c){(0,_.Yh)(a,c);c.Sb=5;var f=a.d,g;for(g in f)f[g]==c&&delete f[g]};_.$h=function(a,c){return a.d[c.n]};_.ai=function(a){this.b=a};_.bi=function(){_.Ih.call(this)};
_.ci=function(a){if(window.___jsl.man)a(window.___jsl.man);else if(window.gbar){var c=function(){var c=new _.ai(window.gbar.wg);window.___jsl.man=c;a(c)};window.gbar.wg?c():window.gbar.qm(c)}else c=new _.bi,window.___jsl.man=c,a(c)};_.di=function(){return window.___jsl.man};_.Gh.prototype.xe=(0,_.z)("ue");_.Gh.prototype.isEnabled=(0,_.z)("rp");_.Gh.prototype.Ra=(0,_.da)("rp");
_.D=_.Ih.prototype;_.D.pk=function(a,c,f){try{a=a+(c!=_.q?"_"+c:""),f.sm(this.b,a),this.d[a]=new _.Gh(f)}catch(g){return _.v}return _.p};_.D.bm=function(a,c){var f=this.d[a+(c!=_.q?"_"+c:"")];return f?f.xe():_.q};_.D.Ck=function(a){var c=(0,_.$h)(this,a);if(c&&(2==c.Sb||3==c.Sb)&&c.isEnabled()&&!c.ti){try{a.sh()}catch(f){}c.ti=_.p}};_.D.Oh=function(a){var c=(0,_.$h)(this,a);if(c&&(2==c.Sb||3==c.Sb||(0,_.Hh)(c))&&c.ti){try{a.hi()}catch(f){}c.ti=_.v}};
_.D.jh=function(a){var c=(0,_.$h)(this,a);if(c&&5!=c.Sb){try{this.Oh(a),a.cl()}catch(f){}(0,_.Zh)(this,c)}};_.D.iq=function(a){var c=(0,_.$h)(this,a);c&&0==c.Sb&&(this.i?(a=(0,window.setTimeout)((0,_.G)(function(){(0,_.Hh)(c)||(0,_.Jh)(this,c)},this),this.i),c.wi=a):(0,_.Jh)(this,c),c.Sb=1)};_.D.hq=function(a){if((a=(0,_.$h)(this,a))&&!(0,_.Hh)(a)&&1==a.Sb)(0,_.Yh)(this,a),a.Sb=3};_.D.fq=function(a){if((a=(0,_.$h)(this,a))&&!(0,_.Hh)(a))a.ti=_.v};
_.D.dq=function(a){var c=(0,_.$h)(this,a);if(c&&!(0,_.Hh)(c)){try{this.Oh(a)}catch(f){}(0,_.Zh)(this,c)}};_.D.eq=function(a){if((a=(0,_.$h)(this,a))&&!(0,_.Hh)(a))a.Sb=4,this.jh(a.xe())};_.D.gq=function(a,c){var f=(0,_.$h)(this,a);f&&!(0,_.Hh)(f)&&(2<=c&&4>=c&&!(0,_.Hh)(f))&&((0,_.Yh)(this,f),f.Sb=2)};
_.D=_.ai.prototype;_.D.pk=function(a,c,f){return this.b.rc(a,c,f)};_.D.bm=function(a,c){return this.b.fc(a,c)};_.D.Ck=function(a){this.b.sc(a)};_.D.Oh=function(a){this.b.hc(a)};_.D.jh=function(a){this.b.cc(a)};_.D.iq=function(a){this.b.os(a)};_.D.hq=function(a,c){this.b.or(a,c)};_.D.fq=function(a){this.b.oh(a)};_.D.dq=function(a){this.b.oc(a)};_.D.eq=function(a,c,f,g,h,j){this.b.oe(a,c,f,g,h,j)};_.D.gq=function(a,c,f,g){this.b.oi(a,c,f,g)};
(0,_.J)(_.bi,_.Ih);
}catch(e){_._DumpException(e)}
try{
_.ei=function(a){var c=window.document.createElement("div"),f=window.document.createElement("a");f.href=a;c.appendChild(f);c.innerHTML=c.innerHTML;return c.firstChild.href};_.fi=function(a){for(var a=a||"canonical",c=window.document.getElementsByTagName("link"),f=0,g=c.length;f<g;f++){var h=c[f],j=h.getAttribute("rel");if(j&&j.toLowerCase()==a&&(h=h.getAttribute("href")))if(h=(0,_.ei)(h))return h}return window.location.href};_.gi=function(a,c,f,g){return a?(0,_.ei)(a):(0,_.fi)(g)};
_.hi=function(a){return"string"==typeof a?""!=a&&"0"!=a&&"false"!=a.toLowerCase():!!a};_.ii=function(a){var c=(0,window.parseInt)(a,10);if(c==a)return(0,window.String)(c)};_.ji=function(a){if((0,_.hi)(a))return"true"};_.ki=function(a){return"string"==typeof a&&_.li[a.toLowerCase()]?a.toLowerCase():"standard"};_.mi=function(a,c){return"tall"==(0,_.ki)(c)?"true":a==_.q||(0,_.hi)(a)?"true":"false"};_.oi=function(a,c,f){a==_.q&&f&&(a=f.db,a==_.q&&(a=f.gwidget&&f.gwidget.db));return a||_.n};
_.pi=function(a,c,f){a==_.q&&f&&(a=f.ecp,a==_.q&&(a=f.gwidget&&f.gwidget.ecp));return a||_.n};_.li={tall:{"true":{width:50,height:60},"false":{width:50,height:24}},small:{"false":{width:24,height:15},"true":{width:70,height:15}},medium:{"false":{width:32,height:20},"true":{width:90,height:20}},standard:{"false":{width:38,height:24},"true":{width:106,height:24}}};
_.qi={href:[_.gi,"url"],width:[_.ii],size:[_.ki],resize:[_.ji],autosize:[_.ji],count:[function(a,c){return(0,_.mi)(c.count,c.size)}],db:[_.oi],ecp:[_.pi],textcolor:[function(a){if("string"==typeof a&&a.match(/^[0-9A-F]{6}$/i))return a}],drm:[_.ji],recommendations:[],fu:[],ad:[_.ji],cr:[_.ii],ag:[_.ii],"fr-ai":[],"fr-sigh":[]};

}catch(e){_._DumpException(e)}
try{
_.ri=function(a,c){var f=(0,_.Oa)(_.si,a,(0,_.Qa)());return(0,_.Oa)(f,c,(0,_.Qa)())};_.ti=function(a,c,f){var g=_.q;c&&f&&(g=(0,_.ri)(c,f)[a]);return g||_.ui[a]};_.vi=function(a){this.t={};this.tick=function(a,f,g){this.t[a]=[g!=_.n?g:(new window.Date).getTime(),f]};this.tick("start",_.q,a)};
_.wi=function(a,c,f){for(var g=c?c+f:"gapi",h=(0,_.Oa)(_.xi,g,(0,_.Qa)()),j=_.yi[a]||[],m=0;m<j.length;++m){var o=j[m],t=h,u=o[0],w=a,C=c,F=f,o=(0,_.ti)(o[1],C,F),w=(0,_.ti)(w,C,F);t[u]=o&&w?w-o:_.q}_.zi[a]&&_.Ai&&((0,_.Bi)("gapi"),(0,_.Bi)(g,c,f))};_.Ci=function(a,c){for(var c=c||[],f=[],g=0;g<c.length;g++)f.push(a+c[g]);return f};
_.Di=function(a,c,f){var g=[],h="m"+(_.Ei?"1":"0");g.push(h);g.push("l"+((0,_.O)("isPlusUser")?"1":"0"));a&&c&&(a="n"+c,g.push(a),"0"==c&&g.push(h+a));return(0,_.Ci)(f?"e"+f:"",g)};
_.Bi=function(a,c,f){var g=_.wb.__gapi_jstiming__,h=new g.Timer(0);h.name=c||"gapi";var j=_.v,m=_.xi[a];h.tick("_start",_.q,0);for(var o in m)h.tick(o,"_start",m[o]),j=_.p;_.xi[a]=(0,_.Qa)();if(j){a=[];j=(0,_.O)("lexps");a=a.concat((0,_.Ci)("e",j));a=a.concat((0,_.Di)(c,f));for(m=0;m<_.Fi.length;m++)o=_.Fi[m],0<=_.Pa.call(j,o)&&(a=a.concat((0,_.Di)(c,f,o)));a=(0,_.Ci)("abc_",a);g.report(h,{e:a.join(",")})}};_.Gi=function(a,c,f,g){_.zi[f]=_.zi[f]||!!g;(0,_.Oa)(_.yi,f,[]);_.yi[f].push([a,c])}; _.Hi=(0,_.Oa)(_.qb,"perf",(0,_.Qa)());_.ui=(0,_.Oa)(_.Hi,"g",(0,_.Qa)());_.si=(0,_.Oa)(_.Hi,"i",(0,_.Qa)());_.Ii=(0,_.Oa)(_.Hi,"r",[]);_.zi=(0,_.Qa)();_.yi=(0,_.Qa)();
_.Ji=new _.vi;window.__gapi_jstiming__={Timer:_.vi,load:_.Ji};if(window.performance&&window.performance.timing){_.Ki=window.performance.timing;_.Li=window.__gapi_jstiming__.load;_.Mi=_.Ki.navigationStart;_.Ni=_.Ki.responseStart;0<_.Mi&&_.Ni>=_.Mi&&(_.Li.tick("_wtsrt",_.n,_.Mi),_.Li.tick("wtsrt_","_wtsrt",_.Ni),_.Li.tick("tbsd_","wtsrt_"))}
try{_.Oi=_.q;window.chrome&&window.chrome.csi&&(_.Oi=window.Math.floor(window.chrome.csi().pageT),_.Li&&0<_.Mi&&(_.Li.tick("_tbnd",_.n,window.chrome.csi().startE),_.Li.tick("tbnd_","_tbnd",_.Mi)));_.Oi==_.q&&window.gtbExternal&&(_.Oi=window.gtbExternal.pageT());_.Oi==_.q&&window.external&&(_.Oi=window.external.pageT,_.Li&&0<_.Mi&&(_.Li.tick("_tbnd",_.n,window.external.startE),_.Li.tick("tbnd_","_tbnd",_.Mi)));_.Oi&&(window.__gapi_jstiming__.pt=_.Oi)}catch(Pi){};
if(window.__gapi_jstiming__){window.__gapi_jstiming__.ap={};window.__gapi_jstiming__.Nw=1;_.Qi=function(a,c,f){var g=a.t[c],h=a.t.start;if(g&&(h||f))return g=a.t[c][0],f!=_.n?h=f:h=h[0],g-h};window.__gapi_jstiming__.getTick=_.Qi;window.__gapi_jstiming__.getLabels=function(a){var c=[],f;for(f in a.t)c.push(f);return c};_.Ri=function(a,c,f){var g="";window.__gapi_jstiming__.pt&&(g+="&srt="+window.__gapi_jstiming__.pt);try{window.external&&window.external.tran?g+="&tran="+window.external.tran:window.gtbExternal&&
window.gtbExternal.tran?g+="&tran="+window.gtbExternal.tran():window.chrome&&window.chrome.csi&&(g+="&tran="+window.chrome.csi().tran)}catch(h){}var j=window.chrome;if(j&&(j=j.loadTimes)){j().wasFetchedViaSpdy&&(g+="&p=s");if(j().wasNpnNegotiated){var g=g+"&npn=1",m=j().npnNegotiatedProtocol;m&&(g+="&npnv="+(window.encodeURIComponent||window.escape)(m))}j().wasAlternateProtocolAvailable&&(g+="&apa=1")}var o=a.t,t=o.start,j=[],m=[],u;for(u in o)if("start"!=u&&0!=u.indexOf("_")){var w=o[u][1];w?o[w]&&
m.push(u+"."+(0,_.Qi)(a,u,o[w][0])):t&&j.push(u+"."+(0,_.Qi)(a,u))}if(c)for(var C in c)g+="&"+C+"="+c[C];(c=f)||(c="https:"==window.document.location.protocol?"https://csi.gstatic.com/csi":"http://csi.gstatic.com/csi");a=[c,"?v=3","&s="+(window.__gapi_jstiming__.sn||"gwidget")+"&action=",a.name,m.length?"&it="+m.join(","):"","",g,"&rt=",j.join(",")].join("");if(!a)return"";var g=new window.Image,F=window.__gapi_jstiming__.Nw++;window.__gapi_jstiming__.ap[F]=g;g.onload=g.onerror=function(){window.__gapi_jstiming__&&
delete window.__gapi_jstiming__.ap[F]};g.src=a;g=_.q;return a};window.__gapi_jstiming__.report=function(a,c,f){if("prerender"==window.document.webkitVisibilityState){var g=_.v,h=function(){if(!g){c?c.prerender="1":c={prerender:"1"};var j;"prerender"==window.document.webkitVisibilityState?j=_.v:((0,_.Ri)(a,c,f),j=_.p);j&&(g=_.p,window.document.removeEventListener("webkitvisibilitychange",h,_.v))}};window.document.addEventListener("webkitvisibilitychange",h,_.v);return""}return(0,_.Ri)(a,c,f)}};
_.Fi=[73,74,77,78];_.Ei=window.navigator.userAgent.match(/iPhone|iPad|Android|PalmWebOS|Maemo|Bada/);_.xi=(0,_.Oa)(_.Hi,"_c",(0,_.Qa)());_.Ai=window.Math.random()<((0,_.O)("csi/rate")||0);(0,_.Gi)("blt","bs0","bs1");(0,_.Gi)("psi","ps0","ps1");(0,_.Gi)("wci","wrs","wdc");(0,_.Gi)("wdi","wrs","wrdi");(0,_.Gi)("wdt","bs0","wrdt");(0,_.Gi)("wri","wrs","wrri",_.p);(0,_.Gi)("wrt","bs0","wrrt");(0,_.Gi)("wji","wje0","wje1",_.p);(0,_.Gi)("wjli","wjl0","wjl1");(0,_.Gi)("rpcqi","rqe","rqd"); if("function"!==typeof _.Ii){for(_.Si;_.Si=_.Ii.shift();)_.wi.apply(_.q,_.Si);_.Ii=_.Hi.r=_.wi};

}catch(e){_._DumpException(e)}
try{
_.Ti=function(a,c,f){"function"===typeof _.Ii?(0,_.Ii)(a,c,f):_.Ii.push([a,c,f])};_.Ui=function(a,c){if("string"==typeof a){var f;for(f=0;f<c.length;f++)if(c[f]==a.toLowerCase())return a.toLowerCase()}};_.Vi=function(a,c){return window.Object.prototype.hasOwnProperty.call(a,c)};_.Lj=function(a,c,f,g){(0,_.ri)(c,f)[a]=g||(new window.Date).getTime();(0,_.Ti)(a,c,f)};_.Mj=function(a){return(0,_.Ui)(a,_.Nj)};_.Oj=function(a){return(0,_.Ui)(a,_.Pj)};
_.Qj=function(){return window.location.origin||window.location.protocol+"//"+window.location.host};_.Rj=function(a){var c=[];if(a)for(var f in a)(0,_.Vi)(a,f)&&a[f]!=_.q&&c.push((0,window.encodeURIComponent)(f)+"="+(0,window.encodeURIComponent)(a[f]));return c};_.Sj=function(a){a.source=[_.q,"source"];a.expandTo=[_.q,"expandTo"];a.align=[_.Oj];a.annotation=[_.Mj];a.origin=[_.Qj]};
_.Tj=function(a,c,f){var a=a.match(_.Uj),g=(0,_.Qa)();g.ne=a[1];g.Xc=a[3]?[a[3]]:[];g.oj=a[5]?[a[5]]:[];g.Xc.push.apply(g.Xc,(0,_.Rj)(c));g.oj.push.apply(g.oj,(0,_.Rj)(f));return g.ne+(0<g.Xc.length?"?"+g.Xc.join("&"):"")+(0<g.oj.length?"#"+g.oj.join("&"):"")};_.Xj=function(a,c){var a=a||{},f;for(f in a)(0,_.Vi)(a,f)&&(c[f]=a[f])};_.Yj=function(a){return(0,window.String)(a).replace(_.Zj,"&amp;").replace(_.$j,"&lt;").replace(_.ak,"&gt;").replace(_.bk,"&quot;").replace(_.ck,"&#39;")};
_.dk=function(a,c,f){return(0,_.gi)(a,c,f,c.action?_.q:"publisher")};_.ek=function(a,c){if(!_.fk){var f=(0,_.O)("iframes/:socialhost:"),g=(0,_.jg)(_.n)||"0",h=(0,_.jg)(_.n);_.fk={socialhost:f,session_index:g,session_prefix:h!==_.n&&h!==_.q&&""!==h?"u/"+h+"/":""}}return _.fk[c]||""};
_.gk=function(a,c,f,g){if(!c.parentNode)return _.q;if(!g){for(var g=(0,_.Qa)(),h=0!=c.nodeName.toLowerCase().indexOf("g:"),j=0,m=c.attributes.length;j<m;j++){var o=c.attributes[j],t=o.name,o=o.value;0<=_.Pa.call(_.hk,t)||(h&&0!=t.indexOf("data-")||"null"===o)||(h&&(t=t.substr(5)),g[t.toLowerCase()]=o)}h=c.style;(j=(0,_.ik)(h&&h.height))&&(g.height=(0,window.String)(j));(h=(0,_.ik)(h&&h.width))&&(g.width=(0,window.String)(h))}h=a;"plus"==a&&g.action&&(h=a+"_"+g.action);(h=(0,_.O)("iframes/"+h+"/url"))||
(h=":socialhost:/_/widget/render/"+a);h=h.replace(_.jk,_.ek);j={};(0,_.Xj)(g,j);j.hl=(0,_.O)("lang")||"en-US";j.origin=(0,_.Qj)();"plus"===a&&(j.url=(0,_.dk)(j.href,g,_.q),delete j.href);"plusone"===a&&(j.url=g.href?(0,_.ei)(g.href):(0,_.fi)(),j.db=(0,_.oi)(g.db,_.n,(0,_.O)()),j.ecp=(0,_.pi)(g.ecp,_.n,(0,_.O)()),delete j.href);j.hl=(0,_.O)("lang")||"en-US";_.qb.ILI&&(j.iloader="1");delete j["data-onload"];delete j.rd;m=(0,_.O)("inline/css");"undefined"!==typeof m&&(0<f&&m>=f)&&(j.ic="1");var m=/^#|^fr-/,
f={},u;for(u in j)(0,_.Vi)(j,u)&&m.test(u)&&(f[u.replace(m,"")]=j[u],delete j[u]);u=[].concat(_.kk);m=(0,_.O)("iframes/"+a+"/methods");"object"===typeof m&&_.Ua.test(m.push)&&(u=u.concat(m));for(var w in g)if((0,_.Vi)(g,w)&&/^on/.test(w)&&("plus"!=a||"onconnect"!=w))u.push(w),delete j[w];f._methods=u.join(",");h=(0,_.Tj)(h,j,f);g.rd?w=c:(w=window.document.createElement("div"),c.setAttribute("data-gapistub",_.p),w.style.cssText="position:absolute;width:100px;left:-10000px;",c.parentNode.insertBefore(w,
c));w.id||(c=w,(0,_.Oa)(_.lk,a,0),u="___"+a+"_"+_.lk[a]++,c.id=u);c=(0,_.Qa)();c[">type"]=a;(0,_.Xj)(g,c);w.setAttribute("data-gwattr",(0,_.Rj)(c).join(":"));var C;u=h;a=w;c={attributes:_.mk};w=a.ownerDocument;j=0;do f=c.id||["I",_.nk++,"_",(new window.Date).getTime()].join("");while(w.getElementById(f)&&5>++j);5>j||(0,_.l)((0,window.Error)("Error creating iframe id"));m=w.location.href;j=(0,_.Qa)();(t=(0,_.ig)(m,"_bsh",_.qb.bsh))&&(j._bsh=t);(m=!_.qb.dpo?(0,_.ig)(m,"jsh",_.qb.h):_.qb.h)&&(j.jsh=
m);var F,m=(0,_.Qa)();m.id=f;m.parent=w.location.protocol+"//"+w.location.host;c.hintInFragment?(0,_.Xj)(j,m):F=j;u=(0,_.Tj)(u,F,m);F=(0,_.Qa)();(0,_.Xj)(_.ok,F);F.name=F.id=f;(0,_.Xj)(c.attributes,F);F.src=u;try{C=w.createElement('<iframe frameborder="'+(0,_.Yj)(F.frameborder)+'" scrolling="'+(0,_.Yj)(F.scrolling)+'" name="'+(0,_.Yj)(F.name)+'"/>')}catch(M){C=w.createElement("iframe")}for(var K in F)c=F[K],"style"==K&&"object"===typeof c?(0,_.Xj)(c,C.style):C.setAttribute(K,F[K]);a.innerHTML="";
a.appendChild(C);F.allowtransparency&&(C.allowTransparency=_.p);K={};K.userParams=g;K.url=h;K.iframeNode=C;K.id=C.getAttribute("id");return K};_.ik=function(a){var c=_.n;"number"===typeof a?c=a:"string"===typeof a&&(c=(0,window.parseInt)(a,10));return c};
_.pk=function(a,c){_.ui.ps0=(new window.Date).getTime();(0,_.Ti)("ps0");var f=("string"===typeof a?window.document.getElementById(a):a)||_.xb,g,h=_.xb.documentMode;if(f.querySelectorAll&&(!h||8<h)){if(c)g=[c];else if(_.Ua.test(window.Object.keys))g=window.Object.keys(_.qk);else{h=[];for(g in _.qk)(0,_.Vi)(_.qk,g)&&h.push(g);g=h}for(var h=[],j=0;j<g.length;j++){var m=g[j];h.push(".g-"+m,"g\\:"+m)}g=f.querySelectorAll(h.join(","))}else g=f.getElementsByTagName("*");f=(0,_.Qa)();for(h=0;h<g.length;h++){j=
g[h];var o=j,m=c,t=o.nodeName.toLowerCase(),u=_.n;o.getAttribute("data-gapiscan")?m=_.q:(0==t.indexOf("g:")?u=t.substr(2):(o=(o=(0,window.String)(o.className||o.getAttribute("class")))&&_.rk.exec(o))&&(u=o[1]),m=u&&_.qk[u]&&(!m||u===m)?u:_.q);m&&(j.setAttribute("data-gapiscan",_.p),(0,_.Oa)(f,m,[]).push(j))}for(var w in f)_.sk.push(w);_.ui.ps1=(new window.Date).getTime();(0,_.Ti)("ps1");_.yb.load(_.sk.join(":"),_.n);var C;w=[];for(C in f){g=f[C];h=0;for(j=g.length;h<j;h++)if(m=(0,_.gk)(C,g[h],j))(u=
m.id)&&w.push(u),(0,_.tk)(C,m)}};_.tk=function(a,c){var f=(0,_.Oa)(_.qb,"watt",(0,_.Qa)())[a];c&&f?f(c):_.yb.load(a,function(){var f=(0,_.Oa)(_.qb,"watt",(0,_.Qa)())[a],h=c&&c.iframeNode;!h||!f?(0,_.yb[a].go)(h&&h.parentNode):f(c)})};_.uk=function(a){var c=(0,_.O)(a);return"undefined"!==typeof c?c:(0,_.O)("gwidget/"+a)};_.vk=function(a){return function(c){var f=a;"number"===typeof c?f=c:"string"===typeof c&&(f=c.indexOf("px"),-1!=f&&(c=c.substring(0,f)),f=(0,window.parseInt)(c,10));return f}};
_.wk=function(a){"string"===typeof a&&(a=window[a]);return"function"===typeof a?a:_.q};_.xk=function(a){return a.sx&&window.gbar&&window.gapi.load};_.yk=function(a,c,f,g){return _.X.open(a,c,f,g)};_.zk=function(a,c){for(var f in _.Ak)if(_.Ak.hasOwnProperty(f)){var g=_.Ak[f][1];g&&!c.hasOwnProperty(g)&&(c[g]=a[g])}return c};_.Bk=function(a,c){var f={},g;for(g in a)a.hasOwnProperty(g)&&(f[a[g][1]||g]=(a[g]&&a[g][0]||_.Ck)(c[g],c,_.Dk));return f};
_.Ek=function(a,c,f,g){var h=(0,_.Bk)(a.Oa,f);a.xr.push({element:c,Oa:h,Eg:(0,_.zk)(h,(0,_.Bk)(a.jr,f)),Ig:g,xu:!!f["data-onload"]})};_.Fk=function(a){function c(){for(var c=a.xr,g=a.zn;0<c.length;)g(c.shift())}(0,_.xk)(a)?(0,_.ci)(c):c()};_.Ck=function(a){return a};_.Gk=function(){};_.Hk=function(a){this.d=a;this.b=_.q};_.Nj="inline bubble none only pp vertical-bubble".split(" ");_.Pj=["left","right"];_.Uj=/^([^?#]*)(\?([^#]*))?(\#(.*))?$/;_.ck=/'/g;_.bk=/"/g;_.ak=/>/g;_.$j=/</g;_.Zj=/&/g;_.Ik={};
_.ok={allowtransparency:"true",frameborder:"0",hspace:"0",marginheight:"0",marginwidth:"0",scrolling:"no",style:"",tabindex:"0",vspace:"0",width:"100%"};_.nk=0;_.jk=/:([a-zA-Z_]+):/g;_.mk={style:"position:absolute;top:-10000px;width:300px;margin:0px;borderStyle:none"};_.kk="onPlusOne _ready _close,_open _resizeMe _renderstart oncircled".split(" ");_.fk=_.q;_.lk=(0,_.Oa)(_.qb,"WI",(0,_.Qa)());_.hk=["style","data-gapiscan"];
_.rk=/(?:^|\s)g-((\S)*)(?:$|\s)/;_.qk=(0,_.Qa)();_.sk=(0,_.Oa)(_.qb,"FW",[]);(0,_.Oa)(_.yb,"platform",{}).go=_.pk;_.Kk=["div"];_.Lk="onload";_.Mk=_.p;_.Dk=_.q;_.Dk=(0,_.O)();(0,_.O)("gwidget");_.Nk=(0,_.uk)("parsetags");_.Lk="explicit"===_.Nk||"onload"===_.Nk?_.Nk:_.Lk;_.Ok=(0,_.uk)("google_analytics");"undefined"!==typeof _.Ok&&(_.Mk=!!_.Ok);_.Pk={};_.Pk.width=[(0,_.vk)(450)];_.Pk.height=[(0,_.vk)(24)];_.Pk.callback=[_.wk];_.Pk.onready=[_.wk];_.Pk.lang=[function(){return(0,_.uk)("lang")||"en-US"},"hl"];_.Pk.iloader=[function(){return _.qb.ILI},"iloader"];_.Ak=_.Pk;
_.Jk={Uc:function(a){function c(a){for(var c={},f=0;f<a.length;++f)c[a[f].toLowerCase()]=1;c[j.Ns]=1;j.cn=c}function f(){"onload"===_.Lk&&t.go()}function g(a){var c=a.userParams;if((a=(a=a.iframeNode)&&a.parentNode)&&1===a.nodeType)a.removeAttribute("data-gwattr"),(0,_.Ek)(h,a,c,3);(0,_.Fk)(h)}var h,j={};j.bc=a[0];j.Lk=-1;j.Ms="___"+j.bc+"_";j.Ns="g:"+j.bc;j.Uv="g-"+j.bc;j.xr=[];j.Oa={};j.tl=[];j.Sl=[];a[1]&&(j.jr=a[1]);j.Oa=a[2]||{};for(var m in _.Ak)_.Ak.hasOwnProperty(m)&&!j.Oa.hasOwnProperty(m)&&
(j.Oa[m]=_.Ak[m]);a[3]&&(j.tl=a[3]);a[4]&&c(a[4]);a[5]&&(j.Hg=a[5]);j.sx=a[7]===_.p;j.Fw=a[8];j.cn||c(_.Kk);if(a=a[6])if("number"==typeof a.length){j.Sl=a;for(var o=a.length-1;0<=o;--o)j.Oa[a[o]]=[_.wk]}else for(o in a)a.hasOwnProperty(o)&&!j.Oa.hasOwnProperty(o)&&(j.Sl.push(o),j.Oa[o]=a[o]);j.zn=function(a){function c(){Vj||(Vj=_.p,f(),Wj&&(0,_.Lj)("wrrt",xe,ye),(0,_.Lj)("wrri",xe,ye))}function f(){dh||(dh=_.p,rc.La(),Wj&&(0,_.Lj)("wrdt",xe,ye),(0,_.Lj)("wrdi",xe,ye))}function g(a){var a=a||rc,c=
rc.uj(a.width);c&&eh.style.width!=c.hf&&(eh.style.width=c.hf);if((a=rc.uj(a.height))&&eh.style.height!=a.hf)eh.style.height=a.hf}j.Lk++;(0,_.Lj)("wrs",j.bc,(0,window.String)(j.Lk));var h=[];j.Hg&&(h[0]=a.element,h[1]=a.Ig,j.Hg("s",h),a.Ig=h[1]);var m=a.element,o=m.parentNode,t=a.Oa;if(0===a.Ig){var w=window.document.createElement("div");o.insertBefore(w,m);o.removeChild(m);m=w}w=m.style;if(m.id){if(3===a.Ig&&0===m.id.indexOf(j.Ms)){var u=m.nextSibling;u&&(u.getAttribute&&u.getAttribute("data-gapistub"))&&
o.removeChild(u);w.cssText=""}}else{var o=m,u=j.Ms,C=j.bc,Ba=(0,_.Oa)(_.qb,"WI",(0,_.Qa)());window.Object.prototype.hasOwnProperty.call(Ba,C)||(Ba[C]=0);var sc=Ba[C];Ba[C]=sc+1;o.id=u+sc}t.height&&(w.height=t.height+"px");t.width&&(w.width=t.width+"px");w.display||(w.display="inline-block");(0,_.xk)(j)&&(w.display="none");(0,_.Ah)(m);var ud=":"+j.bc;":plus"==ud&&(a.Eg&&a.Eg.action)&&(ud+="_"+a.Eg.action);var w={},o=j.tl[0],u=t.callback,ni=j.tl[1];if(ni&&_.Mk)var Tm=u||(0,_.x)(),u=function(a){var c=
ni(a);if(c&&window._gat)try{var f=window._gat._getTrackerByName("~0");f&&"UA-XXXXX-X"!=f._getAccount()?f._trackSocial("Google",c,a.href||_.q):window._gaq&&window._gaq.push(["_trackSocial","Google",c,a.href||_.q])}catch(g){}Tm(a)};o&&u&&(w[o]=u);o=j.Sl;for(u=o.length-1;0<=u;--u){var fc=o[u];(C=t[fc])&&(w[fc]=C)}o={};for(fc in a.Eg)a.Eg[fc]!=_.q&&(o[fc]=a.Eg[fc]);fc={container:m.id,style:"inline",height:t.height,width:t.width};if(3===a.Ig){if(!_.X.Ga("attach")){var Ae={},cg=_.X.Ga("inline"),Xc;for(Xc in cg)cg.hasOwnProperty(Xc)&&
(Ae[Xc]=cg[Xc]);Ae.open=function(a){var c;a:{c=window.document.getElementById(a.Ha().container).getElementsByTagName("IFRAME");for(var f=0;f<c.length;++f){var g=c[f];if(g.id&&/^I\d+_\d+$/.test(g.id)){c=g;break a}}c=_.n}return c?cg.attach(a,c):cg.open(a)};_.X.Sa("attach",Ae)}fc.style="attach"}else if((0,_.xk)(j)){fc._ct=j.bc;fc._ci=j.Lk;if(!_.X.Ga("inline-managed")){Xc={};var dg=_.X.Ga("inline");for(Ae in dg)dg.hasOwnProperty(Ae)&&(Xc[Ae]=dg[Ae]);Xc.open=function(a){dg.open(a);var c=new _.Fh(new _.Hk(a));
(0,_.di)().pk(a.Ha()._ct,a.Ha()._ci,c)&&(a=c[_.Ik.et.jt],a.b&&(a=a.b,a.b.os(a.ue)))};Xc.onready=function(a){dg.onready(a);var c=(0,_.di)();if(a=c.bm(a.Ha()._ct,a.Ha()._ci)){var f=a[_.Ik.et.jt];f.b&&f.b.p({});c.Ck(a)}};_.X.Sa("inline-managed",Xc)}fc.style="inline-managed"}j.Hg&&(h[2]=fc,h[3]=o,h[4]=w,j.Hg("i",h),a.Ig=h[1]);var rc=function(a){var c=_.yk.apply(_.q,[ud].concat([].slice.call(arguments,0)));if(t.onready){var f=_.v,g=function(){f||(f=_.p,t.onready.call(_.q))};c.Ca("ready",g);c.Ca("renderstart",
g)}(0,_.Gk)(c);return c}(fc,o,w),eh=m;rc.Ca("ready",g);rc.Ca("renderstart",g);rc.Ca("resize",g);var Wj=a.xu,xe=j.bc,ye=(0,window.String)(j.Lk),dh=_.v;rc.Ca("renderstart",f);var Vj=_.v;rc.Ca("ready",c);_.S.ea("widget-interactive-"+rc.id,c);_.S.ea("widget-csi-tick-"+rc.id,function(a,c,f){"wdc"===a||"wci"===a?(0,_.Lj)("wdc",xe,ye,f):"wje0"===a||"wji_"===a?(0,_.Lj)("wje0",xe,ye,f):("wje1"===a||"wji"===a)&&(0,_.Lj)("wje1",xe,ye,f)});h[5]=rc;j.Hg&&j.Hg("e",h)};h=j;if(o=h.Fw)for(a=0;a<o.length;a++)(new window.Image).src=
o[a];var t={fa:function(a,c,f){a=("string"===typeof a?window.document.getElementById(a):a)||_.n;c=c||{};c.callback=f||c.callback;a&&1===a.nodeType&&(0,_.Ek)(h,a,c,1);(0,_.Fk)(h)},go:function(a){if(a=("string"===typeof a?window.document.getElementById(a):a)||window.document.body){var c;c=h;for(var f=[],g=a.getElementsByTagName("iframe"),j={},m=0;m<g.length;++m){var o=g[m].parentNode,t=o.id;if(t&&!j[t]){var w;a:{w=c;var u=o,C=u.getAttribute("data-gwattr");if(C!=_.q){for(var C=C.split(":"),Ba={},sc=
0;sc<C.length;++sc){var ud=C[sc].split("="),ni=window.decodeURIComponent(ud[0]),ud=window.decodeURIComponent(ud[1]);Ba[ni]=ud}if(Ba[">type"]===w.bc){u.removeAttribute("data-gwattr");w=Ba;break a}}w=_.n}w&&(f.push({element:o,ql:w}),j[t]=1)}}c=f;for(f=0;f<c.length;++f)g=c[f],(0,_.Ek)(h,g.element,g.ql,3);c=h;f=[];a=a.getElementsByTagName("*");g=(0,window.RegExp)("(?:^|\\s)"+c.Uv+"(?:$|\\s)");for(j=0;j<a.length;++j)if(m=a[j],o=m.nodeName.toLowerCase(),!m.getAttribute("data-gapistub")&&(c.cn[o]||c.cn["*"])){t=
"";if(o!==c.Ns&&(t="data-",!g.test(m.className||m.getAttribute("class"))))continue;w=o={};u=c.jr;C=m;Ba=t;sc=_.n;for(sc in u)u.hasOwnProperty(sc)&&(w[sc]=C.getAttribute(Ba+sc));w=o;u=c.Oa;C=m;Ba=_.n;for(Ba in u)u.hasOwnProperty(Ba)&&(w[Ba]=C.getAttribute(t+Ba));f.push({element:m,ql:o})}c=f;for(f=0;f<c.length;++f)g=c[f],(0,_.Ek)(h,g.element,g.ql,0);(0,_.Fk)(h)}},b:function(){_.qb.WI=(0,_.Qa)()}};if((o=(0,_.O)("lexps"))&&0<=_.Pa.call(o,75))o=h.bc,a=(0,_.Oa)(_.qb,"watt",(0,_.Qa)()),(0,_.Oa)(a,o,g),_.qk[h.bc]=
1,t.go=function(a){(0,_.pk)(a,h.bc)},t.fa=function(a,c){var f=c||{};f.type=h.bc;var g=f,f=g.type;delete g.type;if(!f||!_.qk[f])(0,_.l)((0,window.Error)("Unsupported widget "+f||""));var j=("string"===typeof a?window.document.getElementById(a):a)||_.n;if(j&&1===j.nodeType){var m={},o;for(o in g)(0,_.Vi)(g,o)&&(m[o.toLowerCase()]=g[o]);g=m;g.rd=1;o=(0,_.gk)(f,j,0,g);(0,_.tk)(f,o)}};o=h.bc;a=(0,_.Oa)(_.qb,"sws",[]);if(!(0<=_.Pa.call(a,o))){if("complete"!==_.xb.readyState)try{f()}catch(u){}if("complete"===
_.xb.readyState)f();else{var w=_.v,C=function(){if(!w)return w=_.p,f.apply(this,arguments)};_.wb.addEventListener?(_.wb.addEventListener("load",C,_.v),_.wb.addEventListener("DOMContentLoaded",C,_.v)):_.wb.attachEvent&&(_.wb.attachEvent("onreadystatechange",function(){"complete"===_.xb.readyState&&C.apply(this,arguments)}),_.wb.attachEvent("onload",C))}}return t}};
_.Ik=_.Ik||{};_.D=_.Hk.prototype;_.D.Or=(0,_.da)("b");_.D.Lp=function(a,c){c({})};_.D.show=function(){this.d.na().style.display="inline-block"};_.D.oq=function(){this.d.na().style.display="none"};_.D.close=function(){this.d.close({})};_.D.enable=(0,_.x)();_.D.disable=(0,_.x)();

}catch(e){_._DumpException(e)}
try{
_.gC=(window.gapi||{}).load;
}catch(e){_._DumpException(e)}
try{
_.X.zk("bubble",function(a){(0,_.gC)("iframes-styles-bubble",a)});
}catch(e){_._DumpException(e)}
try{
_.X.zk("slide-menu",function(a){(0,_.gC)("iframes-styles-slide-menu",a)});
}catch(e){_._DumpException(e)}
try{

}catch(e){_._DumpException(e)}
try{
_.sR=function(a,c,f){a=(0,_.Mj)(a);c=(0,_.ki)(c);if(""!=a){if("inline"==a||"only"==a)return a=450,f.width&&(a=120<f.width?f.width:120),{width:a,height:_.li[c]["false"].height};if("bubble"!=a){if("none"==a)return _.li[c]["false"];if("pp"==a)return _.tR}}return _.li[c]["true"]};_.tR={width:180,height:35};_.uR={"0":"plusone"};_.vR=(0,_.O)("iframes/plusone/preloadUrl");_.vR&&(_.uR[8]=_.vR);(0,_.Sj)(_.qi);_.uR[1]=_.qi;
_.uR[2]={width:[function(a,c){return c.annotation?(0,_.sR)(c.annotation,c.size,c).width:_.li[(0,_.ki)(c.size)][(0,_.mi)(c.count,c.size)].width}],height:[function(a,c){return c.annotation?(0,_.sR)(c.annotation,c.size,c).height:_.li[(0,_.ki)(c.size)][(0,_.mi)(c.count,c.size)].height}]};_.uR[3]=["onPlusOne",function(a){return"on"==a.state?"+1":_.q}];_.uR[4]=["div","button"];_.uR[6]=["onstartinteraction","onendinteraction","onpopup"];_.Jb=_.Ob=_.Jk.Uc(_.uR);
(0,_.Q)("gapi.plusone.render",_.Ob.fa);(0,_.Q)("gapi.plusone.go",_.Ob.go);(0,_.Q)("googleapisv0.plusone.render",_.Jb.fa);(0,_.Q)("googleapisv0.plusone.go",_.Jb.go);
}catch(e){_._DumpException(e)}
});

// Copyright 2002-2012 Google Inc.
